#!/bin/bash
# Block edits to auto-generated config files (PreToolUse on Write, Edit)
#
# docker-compose.override.yml is generated by provision
# (scripts/worktree/_derive.sh) into .worktree-run/ and should never be edited
# by hand or by AI agents.

set -e

INPUT=$(cat)

# Get the file path being modified
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
    exit 0
fi

# Extract just the filename
BASENAME=$(basename "$FILE_PATH")

# Check against protected files
case "$BASENAME" in
    docker-compose.override.yml)
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "  BLOCKED: $BASENAME is auto-generated"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "  This file is generated by provision (scripts/worktree/_derive.sh)"
        echo "  into .worktree-run/. Do not edit it directly."
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        exit 2
        ;;
esac

exit 0
