"""Phase C: Cross-model plan verification (~$3-5 per invocation).

Dispatches a Codex agent to adversarially verify the Opus-generated plan.
Checks 5 dimensions: journey completeness, transition coverage, intent
alignment, gap detection, and validation sufficiency.

This runs AFTER Phase A deterministic validation passes. Phase C catches
what deterministic checks cannot: narrative completeness, intent alignment,
and logical gaps between stories. Using a different model family provides
genuine cross-model verification.

Reference: Research doc Section 8.4 Decision 8.

One revision cycle is budgeted: planner -> verifier -> planner -> verifier.
If the second attempt also fails Phase B, exit to human.

Usage:
    python -m workflow.plan_verifier <epic_number>
"""

import json
import logging
import sys
from pathlib import Path

from workflow.dispatch import (
    dispatch_agent,
    extract_json_from_text,
    get_dispatch_params,
)
from workflow.epic_config import EpicConfig
from workflow.models import Plan, render_plan_md
from workflow.plan_generator import (
    PlanGenerationError,
    _parse_structured_plan,
    build_targeted_phase_a_revision_prompt,
    build_targeted_phase_b_revision_prompt,
)
from workflow.plan_validator import validate_plan

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PLANNING_DIR = PROJECT_ROOT / ".planning" / "epics"

logger = logging.getLogger(__name__)


class PlanVerificationError(Exception):
    """Raised when plan verification fails unrecoverably."""


# ---------------------------------------------------------------------------
# Verifier prompt construction
# ---------------------------------------------------------------------------


def _build_verifier_prompt(
    plan_json: dict,
    epic_md: str,
    context_md: str,
) -> str:
    """Construct the Codex verifier prompt with cross-model framing."""
    plan_json_str = json.dumps(plan_json, indent=2)

    prompt = f"""\
# Task: Verify Epic Plan (Adversarial Review)

You are reviewing a plan generated by a separate AI agent. Your job is
adversarial: find flaws, not confirm correctness. The planner had its own
context and biases — bring fresh eyes and challenge every assumption.

You must check 5 dimensions and return structured JSON output.

---

## Input 1: Original Epic (from GitHub)

<epic>
{epic_md}
</epic>

## Input 2: Assembled Context

<context>
{context_md}
</context>

## Input 3: Generated Plan (plan.json)

<plan>
{plan_json_str}
</plan>

---

## Verification Dimensions

Check each dimension independently.

### Severity Classification

Every finding MUST have a severity level:

- **must_fix**: The plan will produce incorrect or incomplete results if this
  is not addressed. Examples: missing story for a required feature, no
  validation for a critical user path, a story that contradicts the epic.
- **note**: An observation worth reporting but not blocking. Examples:
  a test could be more thorough, a defensive fallback was added beyond
  the spec, a checkpoint implicitly covers something rather than
  explicitly naming it.

**A dimension passes if it has zero `must_fix` findings.** Dimensions with
only `note` findings still pass. Do NOT fail a dimension for observations
that are merely imperfect rather than broken.

### 1. Journey Completeness

Do the user journeys cover the full scope of the epic? Walk through each
journey narrative and verify:
- Every step in the narrative has a corresponding story that builds it
- Every step has a validation checkpoint that verifies it (either directly
  or as part of a broader checkpoint)
- Flag any step in a journey that no story addresses

Set `gaps` to an empty array if all journeys are complete.

### 2. Transition Coverage

Are all `critical_transitions` in the journeys covered by validation
checkpoints? For each transition:
- There must be a checkpoint verifying the source page renders correctly
- There must be a checkpoint verifying the transition mechanism works
  (link exists, form submits, etc.)
- There must be a checkpoint verifying the target page renders correctly

Flag transitions that fall between checkpoints (i.e., no checkpoint
verifies them). Set `uncovered` to an empty array if all transitions
are covered.

### 3. Intent Alignment

Does the plan deliver what the epic asks for? Compare the epic's
requirements against the plan's stories:
- Flag epic requirements that have no corresponding story
  (unaddressed_requirements)
- Flag stories that address requirements not in the epic
  (scope_creep)

Set both arrays to empty if alignment is perfect.

### 4. Gap Detection

Are there logical gaps between stories? Walk the dependency chain for
each feature:
- entity -> ORM model -> repository -> service -> API endpoint ->
  page template -> navigation link
- Every link in the chain must exist in some story's scope
- If Story 1 creates an entity and Story 3 builds UI for it, but no
  story creates the API endpoint connecting them, flag the gap

Chains that stay within a single story (e.g. route -> response with no
persistence layer) do not need to be flagged as gaps.

Set `gaps` to an empty array if no logical gaps exist.

### 5. Validation Sufficiency

Are the validation checkpoints strong enough to catch real failures?
For each checkpoint, ask: "If this check passes, does it prove the
feature works, or could it false-green?"

Flag checks that:
- Verify existence but not function (e.g., "page returns 200" without
  checking content)
- Miss critical user-facing behaviour
- Could pass even if the feature is broken

A test that asserts field presence and correct values is sufficient — it
does not also need to assert the exact key count or negative-auth cases
unless the epic explicitly requires it.

Set `weak_checks` to an empty array if all checkpoints are sufficient.

---

## What You Do NOT Check

- Whether implementation notes are correct (runtime discovery)
- Whether file paths in scope are the best choice (planner's domain)
- Whether story sizing is optimal (learned from experience)
- Subjective plan quality (human's job at Decision Gate)
- Whether defensive defaults (fallback values) are appropriate — that is
  an implementation detail, not a plan flaw
- Whether CI/CD or deployment pipelines set environment variables — that
  is outside the scope of the code plan

---

## Output

Your ENTIRE response must be a single JSON object — no markdown, no analysis text,
no explanation before or after. Output ONLY the JSON object.

The JSON must have this structure:
- "status": "pass" or "fail" (fail if ANY dimension has must_fix findings)
- "dimensions": object with keys for each dimension, each containing:
  - "status": "pass" or "fail" (fail only if must_fix findings exist)
  - "findings": array of objects, each with "severity" ("must_fix" or "note"),
    plus the dimension-specific fields
- "summary": brief overall summary string

Be rigorous but fair. Flag real issues, not stylistic preferences. A plan
that covers the epic's requirements with reasonable tests passes — it does
not need to be perfect.
"""

    return prompt


# ---------------------------------------------------------------------------
# Result parsing
# ---------------------------------------------------------------------------


def _parse_verifier_result(result_output: str) -> dict:
    """Parse the verifier agent's output as JSON.

    The prompt instructs the agent to return ONLY a JSON object.
    Agents commonly wrap JSON in markdown code fences, so we strip those.
    """
    try:
        data = extract_json_from_text(result_output or "")
    except ValueError as exc:
        raise PlanVerificationError(
            f"Verifier did not return valid JSON: {exc}\nOutput (first 500 chars): {(result_output or '')[:500]}"
        ) from exc
    if not isinstance(data, dict) or "status" not in data:
        raise PlanVerificationError(
            f"Verifier JSON missing 'status' field. Keys: {list(data.keys()) if isinstance(data, dict) else type(data)}"
        )
    return data


def _is_verifier_pass(result: dict) -> bool:
    """Check if the verifier result indicates an overall pass."""
    return result.get("status") == "pass"


def _get_dimensions(result: dict) -> dict:
    """Extract the dimensions dict, handling both nested and flat layouts.

    The verifier prompt asks for ``{"dimensions": {"journey_completeness": ...}}``,
    but earlier code assumed the dimensions lived at the top level.  Support both.
    """
    dims = result.get("dimensions")
    if isinstance(dims, dict):
        return dims
    # Fallback: dimensions at top level (legacy)
    return result


def _extract_dimension_failures(result: dict) -> list[str]:
    """Extract a summary of failed dimensions for logging."""
    dims = _get_dimensions(result)
    failures = []
    for dimension in [
        "journey_completeness",
        "transition_coverage",
        "intent_alignment",
        "gap_detection",
        "validation_sufficiency",
    ]:
        dim = dims.get(dimension, {})
        if isinstance(dim, dict) and dim.get("status") == "fail":
            failures.append(dimension)
    return failures


def _has_extractable_findings(result: dict) -> bool:
    """Check whether the verifier result contains any must_fix findings.

    Returns False when the verifier reported a fail status but the structured
    output has no extractable content (e.g. empty findings arrays or an
    unexpected format). Used to skip planner revision when there is nothing
    actionable to feed back.
    """
    dims = _get_dimensions(result)
    for dimension in [
        "journey_completeness",
        "transition_coverage",
        "intent_alignment",
        "gap_detection",
        "validation_sufficiency",
    ]:
        dim = dims.get(dimension, {})
        if not isinstance(dim, dict) or dim.get("status") != "fail":
            continue
        findings = dim.get("findings")
        if isinstance(findings, list) and any(
            f.get("severity") == "must_fix" for f in findings if isinstance(f, dict)
        ):
            return True
        if isinstance(findings, dict) and any(findings.values()):
            return True
        # Check flat keys (legacy format)
        for key in ("gaps", "uncovered", "unaddressed_requirements", "scope_creep", "weak_checks"):
            if dim.get(key):
                return True
    return False


# ---------------------------------------------------------------------------
# Decision Gate
# ---------------------------------------------------------------------------


class DecisionGateResult:
    """Result from the human Decision Gate."""

    def __init__(self, decision: str, reason: str = "") -> None:
        if decision not in ("approve", "revise", "reject"):
            raise ValueError(f"Invalid decision: {decision}. Must be approve/revise/reject.")
        self.decision = decision
        self.reason = reason

    @property
    def approved(self) -> bool:
        return self.decision == "approve"

    @property
    def needs_revision(self) -> bool:
        return self.decision == "revise"

    @property
    def rejected(self) -> bool:
        return self.decision == "reject"

    def __repr__(self) -> str:
        return f"DecisionGateResult(decision={self.decision!r}, reason={self.reason!r})"


def _print_plan_summary(plan_md_path: Path) -> None:
    """Print a concise plan summary from plan.json alongside PLAN.md."""
    plan_json_path = plan_md_path.parent / "plan.json"
    if not plan_json_path.is_file():
        return

    try:
        plan_data = json.loads(plan_json_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return

    print(f"\nGoal: {plan_data.get('goal', '?')}")

    stories = plan_data.get("stories", [])
    checkpoints = plan_data.get("validation_checkpoints", [])
    checkpoint_map = {cp["after_story"]: cp for cp in checkpoints}

    print(f"\nStories ({len(stories)}):")
    for story in stories:
        sid = story.get("story_id", "?")
        name = story.get("name", "?")
        purpose = story.get("purpose", "")
        scope = story.get("scope", {})
        create = scope.get("create", [])
        modify = scope.get("modify", [])
        cp = checkpoint_map.get(sid)
        cp_count = len(cp.get("checks", [])) if cp else 0

        print(f"\n  {sid}: {name}")
        print(f"    {purpose}")
        if create:
            print(f"    Create: {len(create)} files")
        if modify:
            print(f"    Modify: {len(modify)} files")
        print(f"    Checks: {cp_count} validation commands")


def present_decision_gate(
    plan_md_path: Path,
    verifier_result: dict,
) -> DecisionGateResult:
    """Present the human with plan summary + verifier report and get a decision."""
    # Display plan location
    print("\n" + "=" * 70)
    print("DECISION GATE")
    print("=" * 70)

    # Show plan summary
    _print_plan_summary(plan_md_path)

    print(f"\nFull plan: {plan_md_path}")
    print(f"Verifier status: {verifier_result.get('status', 'unknown')}")

    # Check for dispatch-level errors (e.g. model credits exhausted)
    dispatch_error = verifier_result.get("error")
    if dispatch_error:
        print(f"\nVerifier error: {dispatch_error}")
        print("(Dimension results unavailable — verifier did not complete)")
    else:
        # Show dimension statuses
        dims = _get_dimensions(verifier_result)
        all_dimensions = [
            "journey_completeness",
            "transition_coverage",
            "intent_alignment",
            "gap_detection",
            "validation_sufficiency",
        ]
        print("\nVerifier dimensions:")
        for dimension in all_dimensions:
            dim = dims.get(dimension, {})
            status = dim.get("status", "unknown") if isinstance(dim, dict) else "unknown"
            if status == "pass":
                icon = "PASS"
            elif status == "fail":
                icon = "FAIL"
            else:
                icon = "SKIP"
            print(f"  [{icon}] {dimension}")

        # Show findings for failed dimensions
        failed_dims = _extract_dimension_failures(verifier_result)
        if failed_dims:
            print(f"\nFailed dimensions: {', '.join(failed_dims)}")
            for dim_name in failed_dims:
                dim = dims.get(dim_name, {})
                if not isinstance(dim, dict):
                    continue
                findings = dim.get("findings", dim)
                # Array of finding objects (current verifier format)
                if isinstance(findings, list):
                    must_fix = [
                        f
                        for f in findings
                        if isinstance(f, dict) and f.get("severity") == "must_fix"
                    ]
                    if must_fix:
                        print(f"\n  {dim_name} ({len(must_fix)} must_fix):")
                        for item in must_fix[:5]:
                            print(f"    - {json.dumps(item, ensure_ascii=False)}")
                        if len(must_fix) > 5:
                            print(f"    ... and {len(must_fix) - 5} more")
                # Dict with named keys (legacy format)
                elif isinstance(findings, dict):
                    for key in [
                        "gaps",
                        "uncovered",
                        "unaddressed_requirements",
                        "scope_creep",
                        "weak_checks",
                    ]:
                        items = findings.get(key, [])
                        if items:
                            print(f"\n  {dim_name}.{key}:")
                            for item in items[:3]:
                                if isinstance(item, dict):
                                    print(f"    - {json.dumps(item)}")
                                else:
                                    print(f"    - {item}")
                            if len(items) > 3:
                                print(f"    ... and {len(items) - 3} more")

    print("\nOptions:")
    print("  [a] Approve — proceed to execution")
    print("  [r] Revise  — re-run planner with findings, then re-verify")
    print("  [x] Reject  — exit, planning artefacts not committed")
    print()

    from workflow.cli import flush_stdin

    while True:
        try:
            flush_stdin()
            choice = input("Decision [a/r/x]: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nRejected (interrupted)")
            return DecisionGateResult("reject", reason="User interrupted")

        if choice == "a":
            return DecisionGateResult("approve")
        elif choice == "r":
            reason = input("Revision notes (optional): ").strip()
            return DecisionGateResult("revise", reason=reason)
        elif choice == "x":
            reason = input("Rejection reason (optional): ").strip()
            return DecisionGateResult("reject", reason=reason)
        else:
            print("Invalid choice. Enter 'a', 'r', or 'x'.")


# ---------------------------------------------------------------------------
# Core verification function
# ---------------------------------------------------------------------------


def verify_plan(
    epic_dir: Path,
    config: EpicConfig | None = None,
) -> dict:
    """Run Phase B cross-model verification on the plan.

    Uses config.models.plan_critic if provided, otherwise falls back to codex.
    """
    # Read inputs
    plan_json_path = epic_dir / "plan.json"
    epic_md_path = epic_dir / "EPIC.md"
    context_md_path = epic_dir / "CONTEXT.md"

    if not plan_json_path.is_file():
        raise PlanVerificationError(f"plan.json not found at {plan_json_path}")
    if not epic_md_path.is_file():
        raise PlanVerificationError(f"EPIC.md not found at {epic_md_path}")
    if not context_md_path.is_file():
        raise PlanVerificationError(f"CONTEXT.md not found at {context_md_path}")

    plan_json = json.loads(plan_json_path.read_text(encoding="utf-8"))
    epic_md = epic_md_path.read_text(encoding="utf-8")
    context_md = context_md_path.read_text(encoding="utf-8")

    # Build the verifier prompt
    prompt = _build_verifier_prompt(
        plan_json=plan_json,
        epic_md=epic_md,
        context_md=context_md,
    )

    critic_model = config.models.plan_critic if config else "opus"

    logger.info(
        "Dispatching %s verifier (%d chars, ~%d tokens)",
        critic_model,
        len(prompt),
        len(prompt) // 4,
    )

    # Dispatch via critic model (cross-model critique)
    mcp_servers, timeout = get_dispatch_params("critique", config)
    result = dispatch_agent(
        prompt=prompt,
        model=critic_model,
        cwd=PROJECT_ROOT,
        mcp_servers=mcp_servers,
        timeout=timeout,
    )

    if not result.success:
        raise PlanVerificationError(
            f"Verifier dispatch failed (exit_code={result.exit_code}). "
            f"Output: {result.output[:500]}"
        )

    # Parse structured output
    verifier_result = _parse_verifier_result(result.output)

    logger.info(
        "Plan verifier result: model=%s, status=%s",
        critic_model,
        verifier_result.get("status", "unknown"),
    )

    return verifier_result


# ---------------------------------------------------------------------------
# Full verification with revision cycle
# ---------------------------------------------------------------------------


def verify_with_revision_cycle(
    epic_dir: Path,
    config: EpicConfig | None = None,
) -> tuple[dict, bool]:
    """Run the full two-phase verification with one revision cycle."""

    # Phase A: Deterministic validation (attempt 1)
    logger.info("Running Phase A validation (attempt 1)...")
    phase_a_result = validate_plan(epic_dir)

    if not phase_a_result.valid:
        logger.warning(
            "Phase A failed with %d errors. Re-invoking planner...",
            len(phase_a_result.errors),
        )

        # Re-invoke planner with validation errors
        try:
            _regenerate_plan_with_errors(epic_dir, phase_a_result.error_messages(), config=config)
        except PlanGenerationError as exc:
            logger.error("Plan regeneration failed: %s", exc)
            return (
                {"status": "fail", "phase_a_errors": phase_a_result.error_messages()},
                False,
            )

        # Re-run Phase A on revised plan
        logger.info("Running Phase A validation (attempt 2, after planner revision)...")
        phase_a_result = validate_plan(epic_dir)
        if not phase_a_result.valid:
            logger.error(
                "Phase A still fails after planner revision (%d errors). Exiting to human.",
                len(phase_a_result.errors),
            )
            return (
                {"status": "fail", "phase_a_errors": phase_a_result.error_messages()},
                False,
            )

    logger.info("Phase A passed. Running Phase B verification...")

    # Phase B: AI verification (attempt 1)
    try:
        verifier_result = verify_plan(epic_dir, config=config)
    except PlanVerificationError as exc:
        logger.error("Phase B dispatch failed: %s", exc)
        return ({"status": "fail", "error": str(exc)}, False)

    if _is_verifier_pass(verifier_result):
        logger.info("Phase B passed. Plan verified.")
        return (verifier_result, True)

    # Phase B failed — feed verifier output back to planner for revision
    failed_dims = _extract_dimension_failures(verifier_result)
    logger.warning(
        "Phase B failed (dimensions: %s). Re-invoking planner with verifier feedback...",
        ", ".join(failed_dims),
    )

    # Hard stop: if verifier reported fail but produced no extractable findings,
    # something went wrong with the invocation (instant return, auth failure,
    # malformed output, etc.). Don't waste money on a blind re-plan.
    if not _has_extractable_findings(verifier_result):
        raise PlanVerificationError(
            "Verifier reported fail but contains no extractable must_fix findings. "
            "The verifier may not have run properly. "
            f"Raw result: {json.dumps(verifier_result)[:2000]}"
        )

    # Snapshot the current (Phase A-passing) plan before revision
    plan_json_path = epic_dir / "plan.json"
    plan_md_path = epic_dir / "PLAN.md"
    original_plan_json = plan_json_path.read_text(encoding="utf-8")
    original_plan_md = plan_md_path.read_text(encoding="utf-8") if plan_md_path.exists() else ""

    try:
        _regenerate_plan_with_verifier_feedback(epic_dir, verifier_result, config=config)
    except PlanGenerationError as exc:
        logger.error("Plan regeneration (verifier feedback) failed: %s", exc)
        return (verifier_result, False)

    # Re-run Phase A on revised plan (must still pass after revision)
    logger.info("Running Phase A validation (after verifier revision)...")
    phase_a_result = validate_plan(epic_dir)
    if not phase_a_result.valid:
        logger.warning(
            "Phase A fails after verifier revision (%d errors). "
            "Restoring pre-revision plan and continuing with Phase B failure.",
            len(phase_a_result.errors),
        )
        # Restore the original plan that passed Phase A
        plan_json_path.write_text(original_plan_json, encoding="utf-8")
        if original_plan_md:
            plan_md_path.write_text(original_plan_md, encoding="utf-8")
        logger.info("Restored pre-revision plan.json and PLAN.md.")
        return (verifier_result, False)

    # Phase B: AI verification (attempt 2 — final)
    logger.info("Running Phase B verification (attempt 2, final)...")
    try:
        verifier_result = verify_plan(epic_dir, config=config)
    except PlanVerificationError as exc:
        logger.error("Phase B dispatch failed on second attempt: %s", exc)
        return ({"status": "fail", "error": str(exc)}, False)

    if _is_verifier_pass(verifier_result):
        logger.info("Phase B passed on second attempt. Plan verified.")
        return (verifier_result, True)

    # Second attempt still has findings — present to human at Decision Gate
    failed_dims = _extract_dimension_failures(verifier_result)
    logger.info(
        "Phase B has remaining findings (dimensions: %s). Presenting to human.",
        ", ".join(failed_dims),
    )
    return (verifier_result, False)


# ---------------------------------------------------------------------------
# Plan regeneration helpers
# ---------------------------------------------------------------------------


def _read_original_prompt_context(epic_dir: Path) -> tuple[str, int]:
    """Read CONTEXT.md and extract epic number for prompt reconstruction."""
    import re as _re

    context_path = epic_dir / "CONTEXT.md"
    context = context_path.read_text(encoding="utf-8") if context_path.is_file() else ""

    match = _re.match(r"^E(\d+)$", epic_dir.name)
    epic_number = int(match.group(1)) if match else 0

    return context, epic_number


def _write_plan_from_model(plan: Plan, epic_dir: Path) -> None:
    """Write plan.json and PLAN.md from a validated Plan model."""
    (epic_dir / "plan.json").write_text(
        json.dumps(plan.model_dump(), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (epic_dir / "PLAN.md").write_text(render_plan_md(plan), encoding="utf-8")
    logger.info("Wrote revised plan.json and PLAN.md")


def _regenerate_plan_with_errors(
    epic_dir: Path,
    validation_errors: list[str],
    config: EpicConfig | None = None,
) -> None:
    """Re-invoke the planner with Phase A validation errors.

    Uses a targeted prompt containing only the current plan.json + errors +
    JSON schema (~25K) instead of rebuilding the full planning prompt (~150K).
    """
    plan_json_path = epic_dir / "plan.json"
    plan_json_str = plan_json_path.read_text(encoding="utf-8")

    revision_prompt = build_targeted_phase_a_revision_prompt(plan_json_str, validation_errors)

    planner_model = config.models.planner if config else "opus"

    logger.info(
        "Dispatching %s planner revision (structural errors, %d chars, ~%d tokens)",
        planner_model,
        len(revision_prompt),
        len(revision_prompt) // 4,
    )

    mcp_servers, timeout = get_dispatch_params("planning", config)
    result = dispatch_agent(
        prompt=revision_prompt,
        model=planner_model,
        cwd=PROJECT_ROOT,
        mcp_servers=mcp_servers,
        timeout=timeout,
    )

    if not result.success:
        raise PlanGenerationError(
            f"Planner revision dispatch failed (exit_code={result.exit_code}). "
            f"Output: {result.output[:500]}"
        )

    plan = _parse_structured_plan(result)
    _write_plan_from_model(plan, epic_dir)


def _regenerate_plan_with_verifier_feedback(
    epic_dir: Path,
    verifier_result: dict,
    config: EpicConfig | None = None,
) -> None:
    """Re-invoke the planner with Phase B verifier feedback.

    Uses a targeted prompt containing only the current plan.json + must_fix
    findings + JSON schema (~25K) instead of rebuilding the full planning
    prompt (~150K).
    """
    plan_json_path = epic_dir / "plan.json"
    plan_json_str = plan_json_path.read_text(encoding="utf-8")

    revision_prompt = build_targeted_phase_b_revision_prompt(plan_json_str, verifier_result)

    planner_model = config.models.planner if config else "opus"

    logger.info(
        "Dispatching %s planner revision (verifier feedback, %d chars, ~%d tokens)",
        planner_model,
        len(revision_prompt),
        len(revision_prompt) // 4,
    )

    mcp_servers, timeout = get_dispatch_params("planning", config)
    result = dispatch_agent(
        prompt=revision_prompt,
        model=planner_model,
        cwd=PROJECT_ROOT,
        mcp_servers=mcp_servers,
        timeout=timeout,
    )

    if not result.success:
        raise PlanGenerationError(
            f"Planner revision (verifier feedback) dispatch failed "
            f"(exit_code={result.exit_code}). Output: {result.output[:500]}"
        )

    plan = _parse_structured_plan(result)
    _write_plan_from_model(plan, epic_dir)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """CLI entry point: python -m workflow.plan_verifier <epic_number> [--full-cycle]."""
    if len(sys.argv) < 2:
        print(
            f"Usage: {sys.argv[0]} <epic_number> [--full-cycle]",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        epic_number = int(sys.argv[1])
    except ValueError:
        print(f"Error: epic_number must be an integer, got: {sys.argv[1]}", file=sys.stderr)
        sys.exit(1)

    full_cycle = "--full-cycle" in sys.argv

    epic_dir = PLANNING_DIR / f"E{epic_number}"
    if not epic_dir.is_dir():
        print(f"Error: Epic directory not found: {epic_dir}", file=sys.stderr)
        sys.exit(1)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    if full_cycle:
        verifier_result, success = verify_with_revision_cycle(epic_dir)

        if success:
            print(f"\nPlan verification PASSED for epic #{epic_number}")
            print("All 5 dimensions verified successfully.")
        else:
            print(f"\nPlan verification FAILED for epic #{epic_number}")
            failed = _extract_dimension_failures(verifier_result)
            if failed:
                print(f"Failed dimensions: {', '.join(failed)}")
            if "phase_a_errors" in verifier_result:
                print("Phase A errors:")
                for err in verifier_result["phase_a_errors"]:
                    print(f"  - {err}")

        sys.exit(0 if success else 1)

    else:
        try:
            verifier_result = verify_plan(epic_dir)
        except PlanVerificationError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            sys.exit(1)

        status = verifier_result.get("status", "unknown")
        print(f"\nPhase B verification result: {status}")

        for dimension in [
            "journey_completeness",
            "transition_coverage",
            "intent_alignment",
            "gap_detection",
            "validation_sufficiency",
        ]:
            dim = verifier_result.get(dimension, {})
            dim_status = dim.get("status", "unknown") if isinstance(dim, dict) else "unknown"
            print(f"  [{dim_status.upper()}] {dimension}")

        print(f"\nFull result:\n{json.dumps(verifier_result, indent=2)}")

        sys.exit(0 if status == "pass" else 1)


if __name__ == "__main__":
    main()
