"""Phase B: Cross-model plan verification (~$3-5 per invocation).

Dispatches a Codex agent to adversarially verify the Opus-generated plan.
Checks 5 dimensions: journey completeness, transition coverage, intent
alignment, gap detection, and validation sufficiency.

This runs AFTER Phase A deterministic validation passes. Phase B catches
what deterministic checks cannot: narrative completeness, intent alignment,
and logical gaps between stories. Using a different model family provides
genuine cross-model verification.

One revision cycle is budgeted: planner -> verifier -> planner -> Phase A.
If the revised plan passes Phase A revalidation, accept it and continue.
If it still fails, exit to human.

Usage:
    python -m workflow.plan_verifier <epic_number>
"""

import json
import logging
import sys
from pathlib import Path
from typing import Any

from workflow.artifacts import (
    CurationArtifact,
    EpicArtifact,
    PlanArtifact,
    PlanVerificationResultArtifact,
    RepoFactsArtifact,
    RevisionRequestArtifact,
    VerifierFeedbackArtifact,
)
from workflow.dispatch import (
    dispatch_agent,
    extract_json_from_text,
    get_dispatch_params,
)
from workflow.epic_config import EpicConfig
from workflow.models import Plan
from workflow.plan_generator import (
    PlanGenerationError,
    _parse_structured_plan,
    make_phase_a_revision_prompt,
    make_phase_b_revision_prompt,
)
from workflow.plan_validator import validate_plan
from workflow.prompt_compiler import (
    PromptSection,
    make_prompt_artifact,
    render_json_block,
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PLANNING_DIR = PROJECT_ROOT / ".planning" / "epics"

logger = logging.getLogger(__name__)


class PlanVerificationError(Exception):
    """Raised when plan verification fails unrecoverably."""


# ---------------------------------------------------------------------------
# Verifier prompt construction
# ---------------------------------------------------------------------------


def make_verifier_prompt(
    plan: PlanArtifact,
    epic: EpicArtifact,
    repo_facts: RepoFactsArtifact,
    curation: CurationArtifact | None = None,
):
    """Compile the verifier prompt from typed workflow artifacts."""
    return make_prompt_artifact(
        role="plan_verifier",
        sections=[
            PromptSection(
                "# Task: Verify Epic Plan (Adversarial Review)",
                (
                    "You are reviewing a plan generated by a separate AI agent. Your job is "
                    "adversarial: find flaws, not confirm correctness.\n\n"
                    "**You are a tool-equipped agent.** Use Read, Grep, and Glob to explore the "
                    "codebase and verify the plan's claims.\n\n"
                    "You must check 6 dimensions, explicitly review `contract_decisions`, "
                    "and return structured JSON output."
                ),
            ),
            PromptSection(
                "## Input 1: Original Epic (from GitHub)",
                epic.prompt_block,
            ),
            PromptSection(
                "## Input 2: Generated Plan (review slice)",
                render_json_block("plan", plan.review_payload),
            ),
            PromptSection("## Input 3: Repo Facts", repo_facts.prompt_block),
            *(
                [
                    PromptSection(
                        "## Input 4: Curated Planning Handoff",
                        (
                            "Use this pre-plan curation when judging whether the plan kept the "
                            "intended journey framing, story split, missing assumptions, and "
                            "scope tensions in view.\n\n"
                            f"{curation.prompt_block}"
                        ),
                    )
                ]
                if curation is not None
                else []
            ),
            PromptSection(
                "## Contract Decisions Review",
                """Review `plan.contract_decisions` explicitly.

- If the epic and repo differ on a route, field, transport, or entry point,
  the plan must record a contract decision.
- `contract_decisions[].canonical` may only be `epic` or `bridge`.
- `epic_contract` must preserve the issue contract exactly enough for a human
  reviewer to see the intended surface.
- If canonical is `epic`, stories and checkpoints must still implement the epic
  surface as the user-facing contract.
- If canonical is `bridge`, the bridge must be concrete and checkpoints must
  prove both the epic-facing contract and the compatibility surface.
- If the plan silently substitutes a repo convention or a mismatch exists with
  no recorded contract decision, that is a must_fix failure.""",
            ),
            PromptSection(
                "## Verification Dimensions",
                """### Severity Classification

Every finding MUST have a severity level:

- **must_fix**: The plan will produce incorrect or incomplete results if this is not addressed.
- **note**: Worth reporting but not blocking.

**A dimension passes if it has zero `must_fix` findings.**

### 1. Journey Completeness

- Every journey step must map to a story and checkpoint.
- Flag steps with no story/checkpoint coverage.

### 2. Transition Coverage

- Check source render, transition mechanism, and target render.
- Flag transitions that are not explicitly validated end to end.

### 3. Intent Alignment

- Flag epic requirements with no corresponding story.
- Flag scope creep beyond the epic.
- Flag repo-only substitutions or missing contract decisions.

### 4. Gap Detection

- Walk each feature chain: entity -> repository -> service -> API/page -> navigation.
- Flag missing links between stories.

### 5. Validation Sufficiency

- Flag checkpoints that could false-green.
- Direct 200 checks, grep-only checks, and presence-only checks are weak when the epic requires real behaviour.
- If a bridge is declared, flag missing checkpoints that prove both surfaces.

### 6. Gap Sufficiency

- Flag missed epic gaps, cross-BC gaps, migration gaps, and API/frontend mismatch gaps.""",
            ),
            PromptSection(
                "## What You Do NOT Check",
                """- Whether implementation notes are correct
- Whether file paths are the best choice
- Whether story sizing is optimal
- Subjective plan quality
- CI/CD or deployment pipeline behaviour""",
            ),
            PromptSection(
                "## Output",
                """Your ENTIRE response must be a single JSON object — no markdown, no analysis text.

Return:
- "status": "pass" or "fail"
- "dimensions": object keyed by dimension name with "status" and "findings"
- "summary": brief overall summary

Be rigorous but fair. Flag real issues, not stylistic preferences.""",
            ),
        ],
    )


def _read_optional_curation(epic_dir: Path) -> CurationArtifact | None:
    """Read curation.json from the epic directory when present."""
    curation_path = epic_dir / "curation.json"
    if not curation_path.is_file():
        return None
    try:
        return CurationArtifact.from_epic_dir(epic_dir)
    except ValueError as exc:
        raise PlanVerificationError(str(exc)) from exc


def _build_verifier_prompt(
    plan_json: dict,
    epic_md: str,
    repo_facts_json: dict[str, Any],
    curation_json: dict[str, Any] | None = None,
) -> str:
    """Construct the Codex verifier prompt with cross-model framing.

    The verifier receives the plan.json, original epic body, and repo-facts.
    These grounded inputs replace the old planning-context dependency.
    """
    plan = PlanArtifact.from_dict(plan_json)
    return make_verifier_prompt(
        plan,
        EpicArtifact(epic_number=plan.epic_number, body=epic_md),
        RepoFactsArtifact.from_dict(repo_facts_json),
        None if curation_json is None else CurationArtifact.from_dict(curation_json),
    ).text


# ---------------------------------------------------------------------------
# Result parsing
# ---------------------------------------------------------------------------


def _parse_verifier_result(result_output: str) -> VerifierFeedbackArtifact:
    """Parse the verifier agent's output as JSON.

    The prompt instructs the agent to return ONLY a JSON object.
    Agents commonly wrap JSON in markdown code fences, so we strip those.
    """
    try:
        data = extract_json_from_text(result_output or "")
    except ValueError as exc:
        raise PlanVerificationError(
            f"Verifier did not return valid JSON: {exc}\nOutput (first 500 chars): {(result_output or '')[:500]}"
        ) from exc
    if not isinstance(data, dict) or "status" not in data:
        raise PlanVerificationError(
            f"Verifier JSON missing 'status' field. Keys: {list(data.keys()) if isinstance(data, dict) else type(data)}"
        )
    return VerifierFeedbackArtifact.from_dict(data)


def _is_verifier_pass(result: VerifierFeedbackArtifact) -> bool:
    """Check if the verifier result indicates an overall pass."""
    return result.status == "pass"


def _get_dimensions(result: VerifierFeedbackArtifact) -> dict[str, Any]:
    """Extract the verifier dimensions from a typed feedback artifact."""
    return result.dimensions


def _extract_dimension_failures(result: VerifierFeedbackArtifact) -> list[str]:
    """Extract a summary of failed dimensions for logging."""
    return result.failed_dimensions()


def _has_extractable_findings(result: VerifierFeedbackArtifact) -> bool:
    """Check whether the verifier result contains any must_fix findings.

    Returns False when the verifier reported a fail status but the structured
    output has no extractable content (e.g. empty findings arrays or an
    unexpected format). Used to skip planner revision when there is nothing
    actionable to feed back.
    """
    return result.has_extractable_findings()


# ---------------------------------------------------------------------------
# Decision Gate
# ---------------------------------------------------------------------------


class DecisionGateResult:
    """Result from the human Decision Gate."""

    def __init__(self, decision: str, reason: str = "") -> None:
        if decision not in ("approve", "revise", "reject"):
            raise ValueError(f"Invalid decision: {decision}. Must be approve/revise/reject.")
        self.decision = decision
        self.reason = reason

    @property
    def approved(self) -> bool:
        return self.decision == "approve"

    @property
    def needs_revision(self) -> bool:
        return self.decision == "revise"

    @property
    def rejected(self) -> bool:
        return self.decision == "reject"

    def __repr__(self) -> str:
        return f"DecisionGateResult(decision={self.decision!r}, reason={self.reason!r})"


def _print_plan_summary(plan_md_path: Path) -> None:
    """Print a concise plan summary from plan.json alongside PLAN.md."""
    plan_json_path = plan_md_path.parent / "plan.json"
    if not plan_json_path.is_file():
        return

    try:
        plan_data = json.loads(plan_json_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return

    print(f"\nGoal: {plan_data.get('goal', '?')}")

    stories = plan_data.get("stories", [])
    checkpoints = plan_data.get("validation_checkpoints", [])
    checkpoint_map = {cp["after_story"]: cp for cp in checkpoints}

    print(f"\nStories ({len(stories)}):")
    for story in stories:
        sid = story.get("story_id", "?")
        name = story.get("name", "?")
        purpose = story.get("purpose", "")
        scope = story.get("scope", {})
        create = scope.get("create", [])
        modify = scope.get("modify", [])
        cp = checkpoint_map.get(sid)
        cp_count = len(cp.get("checks", [])) if cp else 0

        print(f"\n  {sid}: {name}")
        print(f"    {purpose}")
        if create:
            print(f"    Create: {len(create)} files")
        if modify:
            print(f"    Modify: {len(modify)} files")
        print(f"    Checks: {cp_count} validation commands")


def present_decision_gate(
    plan_md_path: Path,
    verifier_result: VerifierFeedbackArtifact | PlanVerificationResultArtifact,
) -> DecisionGateResult:
    """Present the human with plan summary + verifier report and get a decision."""
    # Display plan location
    print("\n" + "=" * 70)
    print("DECISION GATE")
    print("=" * 70)

    # Show plan summary
    _print_plan_summary(plan_md_path)

    typed_result = (
        verifier_result
        if isinstance(verifier_result, PlanVerificationResultArtifact)
        else None
    )
    typed_feedback = (
        verifier_result
        if isinstance(verifier_result, VerifierFeedbackArtifact)
        else typed_result.verifier_feedback if typed_result is not None else None
    )

    status = (
        typed_result.status
        if typed_result is not None
        else typed_feedback.status
        if typed_feedback is not None
        else "unknown"
    )
    phase_a_errors = (
        typed_result.phase_a_errors
        if typed_result is not None
        else ()
    )
    dispatch_error = (
        typed_result.error
        if typed_result is not None
        else ""
    )

    print(f"\nFull plan: {plan_md_path}")
    print(f"Verifier status: {status}")

    if phase_a_errors:
        print("\nPhase A errors:")
        for err in phase_a_errors:
            print(f"  - {err}")
    elif dispatch_error:
        print(f"\nVerifier error: {dispatch_error}")
        print("(Dimension results unavailable — verifier did not complete)")
    else:
        assert typed_feedback is not None
        dims = _get_dimensions(typed_feedback)
        all_dimensions = [
            "journey_completeness",
            "transition_coverage",
            "intent_alignment",
            "gap_detection",
            "validation_sufficiency",
            "gap_sufficiency",
        ]
        print("\nVerifier dimensions:")
        for dimension in all_dimensions:
            dim = dims.get(dimension, {})
            status = dim.get("status", "unknown") if isinstance(dim, dict) else "unknown"
            if status == "pass":
                icon = "PASS"
            elif status == "fail":
                icon = "FAIL"
            else:
                icon = "SKIP"
            print(f"  [{icon}] {dimension}")

        failed_dims = _extract_dimension_failures(typed_feedback)
        if failed_dims:
            print(f"\nFailed dimensions: {', '.join(failed_dims)}")
            for dim_name in failed_dims:
                dim = dims.get(dim_name, {})
                if not isinstance(dim, dict):
                    continue
                findings = dim.get("findings", dim)
                # Array of finding objects (current verifier format)
                if isinstance(findings, list):
                    must_fix = [
                        f
                        for f in findings
                        if isinstance(f, dict) and f.get("severity") == "must_fix"
                    ]
                    if must_fix:
                        print(f"\n  {dim_name} ({len(must_fix)} must_fix):")
                        for item in must_fix[:5]:
                            print(f"    - {json.dumps(item, ensure_ascii=False)}")
                        if len(must_fix) > 5:
                            print(f"    ... and {len(must_fix) - 5} more")
                # Dict with named keys (legacy format)
                elif isinstance(findings, dict):
                    for key in [
                        "gaps",
                        "uncovered",
                        "unaddressed_requirements",
                        "scope_creep",
                        "weak_checks",
                    ]:
                        items = findings.get(key, [])
                        if items:
                            print(f"\n  {dim_name}.{key}:")
                            for item in items[:3]:
                                if isinstance(item, dict):
                                    print(f"    - {json.dumps(item)}")
                                else:
                                    print(f"    - {item}")
                            if len(items) > 3:
                                print(f"    ... and {len(items) - 3} more")

    print("\nOptions:")
    print("  [a] Approve — proceed to execution")
    print("  [r] Revise  — re-run planner with findings, then re-verify")
    print("  [x] Reject  — exit, planning artefacts not committed")
    print()

    from workflow.cli import flush_stdin

    while True:
        try:
            flush_stdin()
            choice = input("Decision [a/r/x]: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nRejected (interrupted)")
            return DecisionGateResult("reject", reason="User interrupted")

        if choice == "a":
            return DecisionGateResult("approve")
        elif choice == "r":
            reason = input("Revision notes (optional): ").strip()
            return DecisionGateResult("revise", reason=reason)
        elif choice == "x":
            reason = input("Rejection reason (optional): ").strip()
            return DecisionGateResult("reject", reason=reason)
        else:
            print("Invalid choice. Enter 'a', 'r', or 'x'.")


# ---------------------------------------------------------------------------
# Core verification function
# ---------------------------------------------------------------------------


def verify_plan(
    epic_dir: Path,
    config: EpicConfig | None = None,
) -> VerifierFeedbackArtifact:
    """Run Phase B cross-model verification on the plan.

    Uses config.models.plan_critic if provided, otherwise falls back to codex.
    """
    # Read inputs
    feedback = _verify_plan_artifact(epic_dir, config=config)
    logger.info(
        "Plan verifier result: model=%s, status=%s",
        config.models.plan_critic if config else "opus",
        feedback.status,
    )
    return feedback


def _verify_plan_artifact(
    epic_dir: Path,
    config: EpicConfig | None = None,
) -> VerifierFeedbackArtifact:
    """Run Phase B verification and return a typed verifier feedback artifact."""
    plan_json_path = epic_dir / "plan.json"
    epic_md_path = epic_dir / "EPIC.md"
    repo_facts_path = epic_dir / "repo_facts.json"

    if not plan_json_path.is_file():
        raise PlanVerificationError(f"plan.json not found at {plan_json_path}")
    if not epic_md_path.is_file():
        raise PlanVerificationError(f"EPIC.md not found at {epic_md_path}")
    if not repo_facts_path.is_file():
        raise PlanVerificationError(f"repo_facts.json not found at {repo_facts_path}")

    plan = PlanArtifact.from_path(plan_json_path)
    epic = EpicArtifact.from_epic_dir(epic_dir)
    repo_facts = RepoFactsArtifact.from_path(repo_facts_path)
    curation = _read_optional_curation(epic_dir)

    prompt = make_verifier_prompt(plan, epic, repo_facts, curation).text

    critic_model = config.models.plan_critic if config else "opus"

    logger.info(
        "Dispatching %s verifier (%d chars, ~%d tokens)",
        critic_model,
        len(prompt),
        len(prompt) // 4,
    )

    # Dispatch via critic model (cross-model critique)
    mcp_servers, timeout = get_dispatch_params("critique", config)
    result = dispatch_agent(
        prompt=prompt,
        model=critic_model,
        cwd=PROJECT_ROOT,
        mcp_servers=mcp_servers,
        timeout=timeout,
        role="plan_verifier",
    )

    if not result.success:
        raise PlanVerificationError(
            f"Verifier dispatch failed (exit_code={result.exit_code}). "
            f"Output: {result.output[:500]}"
        )

    # Parse structured output
    return _parse_verifier_result(result.output)


# ---------------------------------------------------------------------------
# Full verification with revision cycle
# ---------------------------------------------------------------------------


def verify_with_revision_cycle(
    epic_dir: Path,
    config: EpicConfig | None = None,
) -> tuple[PlanVerificationResultArtifact, bool]:
    """Run Phase A validation plus a single Phase B critique/revision cycle."""

    # Phase A: Deterministic validation (attempt 1)
    logger.info("Running Phase A validation (attempt 1)...")
    phase_a_result = validate_plan(epic_dir)

    if not phase_a_result.valid:
        logger.warning(
            "Phase A failed with %d errors. Re-invoking planner...",
            len(phase_a_result.errors),
        )

        # Re-invoke planner with validation errors
        try:
            _regenerate_plan_with_errors(epic_dir, phase_a_result.error_messages(), config=config)
        except PlanGenerationError as exc:
            logger.error("Plan regeneration failed: %s", exc)
            return (
                PlanVerificationResultArtifact.from_phase_a_errors(
                    phase_a_result.error_messages()
                ),
                False,
            )

        # Re-run Phase A on revised plan
        logger.info("Running Phase A validation (attempt 2, after planner revision)...")
        phase_a_result = validate_plan(epic_dir)
        if not phase_a_result.valid:
            logger.error(
                "Phase A still fails after planner revision (%d errors). Exiting to human.",
                len(phase_a_result.errors),
            )
            return (
                PlanVerificationResultArtifact.from_phase_a_errors(
                    phase_a_result.error_messages()
                ),
                False,
            )

    logger.info("Phase A passed. Running Phase B verification...")

    # Phase B: AI verification (attempt 1)
    try:
        verifier_feedback = _verify_plan_artifact(epic_dir, config=config)
    except PlanVerificationError as exc:
        logger.error("Phase B dispatch failed: %s", exc)
        return (PlanVerificationResultArtifact.from_error(str(exc)), False)

    if _is_verifier_pass(verifier_feedback):
        logger.info("Phase B passed. Plan verified.")
        result = PlanVerificationResultArtifact.from_verifier_feedback(verifier_feedback)
        return (result, result.passed)

    # Phase B failed — feed verifier output back to planner for revision
    failed_dims = _extract_dimension_failures(verifier_feedback)
    logger.warning(
        "Phase B failed (dimensions: %s). Re-invoking planner with verifier feedback...",
        ", ".join(failed_dims),
    )

    # Hard stop: if verifier reported fail but produced no extractable findings,
    # something went wrong with the invocation (instant return, auth failure,
    # malformed output, etc.). Don't waste money on a blind re-plan.
    if not _has_extractable_findings(verifier_feedback):
        raise PlanVerificationError(
            "Verifier reported fail but contains no extractable must_fix findings. "
            "The verifier may not have run properly. "
            f"Raw result: {json.dumps(verifier_feedback.to_dict())[:2000]}"
        )

    # Snapshot the current (Phase A-passing) plan before revision
    plan_json_path = epic_dir / "plan.json"
    plan_md_path = epic_dir / "PLAN.md"
    original_plan_json = plan_json_path.read_text(encoding="utf-8")
    original_plan_md = plan_md_path.read_text(encoding="utf-8") if plan_md_path.exists() else ""

    try:
        _regenerate_plan_with_verifier_feedback(epic_dir, verifier_feedback, config=config)
    except PlanGenerationError as exc:
        logger.error("Plan regeneration (verifier feedback) failed: %s", exc)
        return (PlanVerificationResultArtifact.from_verifier_feedback(verifier_feedback), False)

    # Re-run Phase A on revised plan (must still pass after revision)
    logger.info("Running Phase A validation (after verifier revision)...")
    phase_a_result = validate_plan(epic_dir)
    if not phase_a_result.valid:
        logger.warning(
            "Phase A fails after verifier revision (%d errors). "
            "Restoring pre-revision plan and continuing with Phase B failure.",
            len(phase_a_result.errors),
        )
        for err in phase_a_result.errors:
            logger.warning("  Phase A error: [%s] %s", err.check, err.message)
        # Restore the original plan that passed Phase A
        plan_json_path.write_text(original_plan_json, encoding="utf-8")
        if original_plan_md:
            plan_md_path.write_text(original_plan_md, encoding="utf-8")
        logger.info("Restored pre-revision plan.json and PLAN.md.")
        return (PlanVerificationResultArtifact.from_verifier_feedback(verifier_feedback), False)

    logger.info(
        "Revised plan passed Phase A revalidation after verifier findings. "
        "Skipping a second Phase B critique and accepting the revised plan."
    )
    return (PlanVerificationResultArtifact.from_revision_success(), True)


# ---------------------------------------------------------------------------
# Plan regeneration helpers
# ---------------------------------------------------------------------------


def _write_plan_from_model(plan: Plan, epic_dir: Path) -> None:
    """Write plan.json and PLAN.md from a validated Plan model."""
    PlanArtifact.from_model(plan).write(epic_dir)
    logger.info("Wrote revised plan.json and PLAN.md")


def _regenerate_plan_with_errors(
    epic_dir: Path,
    validation_errors: list[str],
    config: EpicConfig | None = None,
) -> None:
    """Re-invoke the planner with Phase A validation errors.

    Uses a targeted prompt containing only the current plan.json + errors +
    JSON schema (~25K) instead of rebuilding the full planning prompt (~150K).
    """
    request = RevisionRequestArtifact.for_phase_a(
        PlanArtifact.from_path(epic_dir / "plan.json"),
        validation_errors,
    )
    revision_prompt = make_phase_a_revision_prompt(request).text

    planner_model = config.models.planner if config else "opus"

    logger.info(
        "Dispatching %s planner revision (structural errors, %d chars, ~%d tokens)",
        planner_model,
        len(revision_prompt),
        len(revision_prompt) // 4,
    )

    mcp_servers, timeout = get_dispatch_params("planning", config)
    result = dispatch_agent(
        prompt=revision_prompt,
        model=planner_model,
        json_schema=Plan.model_json_schema(),
        cwd=PROJECT_ROOT,
        mcp_servers=mcp_servers,
        timeout=timeout,
        role="planner_revision",
    )

    if not result.success:
        raise PlanGenerationError(
            f"Planner revision dispatch failed (exit_code={result.exit_code}). "
            f"Output: {result.output[:500]}"
        )

    plan = _parse_structured_plan(result)
    _write_plan_from_model(plan, epic_dir)


def _regenerate_plan_with_verifier_feedback(
    epic_dir: Path,
    verifier_feedback: VerifierFeedbackArtifact,
    config: EpicConfig | None = None,
) -> None:
    """Re-invoke the planner with Phase B verifier feedback.

    Uses a targeted prompt containing only the current plan.json + must_fix
    findings + JSON schema (~25K) instead of rebuilding the full planning
    prompt (~150K).
    """
    request = RevisionRequestArtifact.for_phase_b(
        EpicArtifact.from_epic_dir(epic_dir),
        RepoFactsArtifact.from_epic_dir(epic_dir),
        PlanArtifact.from_path(epic_dir / "plan.json"),
        verifier_feedback,
        _read_optional_curation(epic_dir),
    )
    revision_prompt = make_phase_b_revision_prompt(request).text

    planner_model = config.models.planner if config else "opus"

    logger.info(
        "Dispatching %s planner revision (verifier feedback, %d chars, ~%d tokens)",
        planner_model,
        len(revision_prompt),
        len(revision_prompt) // 4,
    )

    mcp_servers, timeout = get_dispatch_params("planning", config)
    result = dispatch_agent(
        prompt=revision_prompt,
        model=planner_model,
        json_schema=Plan.model_json_schema(),
        cwd=PROJECT_ROOT,
        mcp_servers=mcp_servers,
        timeout=timeout,
        role="planner_revision",
    )

    if not result.success:
        raise PlanGenerationError(
            f"Planner revision (verifier feedback) dispatch failed "
            f"(exit_code={result.exit_code}). Output: {result.output[:500]}"
        )

    plan = _parse_structured_plan(result)
    _write_plan_from_model(plan, epic_dir)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """CLI entry point: python -m workflow.plan_verifier <epic_number> [--full-cycle]."""
    if len(sys.argv) < 2:
        print(
            f"Usage: {sys.argv[0]} <epic_number> [--full-cycle]",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        epic_number = int(sys.argv[1])
    except ValueError:
        print(f"Error: epic_number must be an integer, got: {sys.argv[1]}", file=sys.stderr)
        sys.exit(1)

    full_cycle = "--full-cycle" in sys.argv

    epic_dir = PLANNING_DIR / f"E{epic_number}"
    if not epic_dir.is_dir():
        print(f"Error: Epic directory not found: {epic_dir}", file=sys.stderr)
        sys.exit(1)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    if full_cycle:
        verifier_result, success = verify_with_revision_cycle(epic_dir)

        if success:
            print(f"\nPlan verification PASSED for epic #{epic_number}")
            print("All 5 dimensions verified successfully.")
        else:
            print(f"\nPlan verification FAILED for epic #{epic_number}")
            failed = (
                _extract_dimension_failures(verifier_result.verifier_feedback)
                if verifier_result.verifier_feedback is not None
                else []
            )
            if failed:
                print(f"Failed dimensions: {', '.join(failed)}")
            if verifier_result.phase_a_errors:
                print("Phase A errors:")
                for err in verifier_result.phase_a_errors:
                    print(f"  - {err}")

        sys.exit(0 if success else 1)

    else:
        try:
            verifier_result = verify_plan(epic_dir)
        except PlanVerificationError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            sys.exit(1)

        status = verifier_result.status
        print(f"\nPhase B verification result: {status}")

        for dimension in [
            "journey_completeness",
            "transition_coverage",
            "intent_alignment",
            "gap_detection",
            "validation_sufficiency",
            "gap_sufficiency",
        ]:
            dim = verifier_result.dimension(dimension)
            dim_status = dim.get("status", "unknown") if isinstance(dim, dict) else "unknown"
            print(f"  [{dim_status.upper()}] {dimension}")

        print(f"\nFull result:\n{json.dumps(verifier_result.to_dict(), indent=2)}")

        sys.exit(0 if status == "pass" else 1)


if __name__ == "__main__":
    main()
