name: Task
description: A development task or chore
title: "chore: "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Use this for development tasks, refactoring, documentation, or maintenance work.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: Describe the task...
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      description: Break down the task into steps
      placeholder: |
        - [ ] Step 1
        - [ ] Step 2
        - [ ] Step 3
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional context or considerations
    validations:
      required: false
