"""add shootout and tone_selection tables

Revision ID: 13162ba0b3f0
Revises: d15efa732bff
Create Date: 2025-12-27 01:13:27.452967+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13162ba0b3f0"
down_revision: str | None = "d15efa732bff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shootouts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("di_track_path", sa.String(length=1000), nullable=False),
        sa.Column("di_track_original_name", sa.String(length=255), nullable=False),
        sa.Column("output_format", sa.String(length=10), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("guitar", sa.String(length=255), nullable=True),
        sa.Column("pickup", sa.String(length=255), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("output_path", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_shootouts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shootouts")),
    )
    op.create_index(
        "ix_shootouts_user_created",
        "shootouts",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shootouts_user_id"), "shootouts", ["user_id"], unique=False
    )
    op.create_table(
        "tone_selections",
        sa.Column("shootout_id", sa.Uuid(), nullable=False),
        sa.Column("tone3000_tone_id", sa.Integer(), nullable=False),
        sa.Column("tone3000_model_id", sa.Integer(), nullable=False),
        sa.Column("tone_title", sa.String(length=255), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_size", sa.String(length=20), nullable=False),
        sa.Column("gear_type", sa.String(length=20), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("ir_path", sa.String(length=1000), nullable=True),
        sa.Column("highpass", sa.Boolean(), nullable=False),
        sa.Column("effects_json", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["shootout_id"],
            ["shootouts.id"],
            name=op.f("fk_tone_selections_shootout_id_shootouts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tone_selections")),
    )
    op.create_index(
        op.f("ix_tone_selections_shootout_id"),
        "tone_selections",
        ["shootout_id"],
        unique=False,
    )
    op.create_index(
        "ix_tone_selections_shootout_position",
        "tone_selections",
        ["shootout_id", "position"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tone_selections_tone3000_model_id"),
        "tone_selections",
        ["tone3000_model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tone_selections_tone3000_tone_id"),
        "tone_selections",
        ["tone3000_tone_id"],
        unique=False,
    )
    op.add_column("jobs", sa.Column("shootout_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_jobs_shootout_id"), "jobs", ["shootout_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_jobs_shootout_id_shootouts"),
        "jobs",
        "shootouts",
        ["shootout_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_jobs_shootout_id_shootouts"), "jobs", type_="foreignkey"
    )
    op.drop_index(op.f("ix_jobs_shootout_id"), table_name="jobs")
    op.drop_column("jobs", "shootout_id")
    op.drop_index(
        op.f("ix_tone_selections_tone3000_tone_id"), table_name="tone_selections"
    )
    op.drop_index(
        op.f("ix_tone_selections_tone3000_model_id"), table_name="tone_selections"
    )
    op.drop_index("ix_tone_selections_shootout_position", table_name="tone_selections")
    op.drop_index(op.f("ix_tone_selections_shootout_id"), table_name="tone_selections")
    op.drop_table("tone_selections")
    op.drop_index(op.f("ix_shootouts_user_id"), table_name="shootouts")
    op.drop_index("ix_shootouts_user_created", table_name="shootouts")
    op.drop_table("shootouts")
    # ### end Alembic commands ###
