"""Initial schema

Revision ID: b4a1fd310cb9
Revises:
Create Date: 2026-02-03 20:38:14.374123

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4a1fd310cb9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_makes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gear_makes')),
    sa.UniqueConstraint('name', name=op.f('uq_gear_makes_name'))
    )
    op.create_table('gear_sources',
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gear_sources'))
    )
    op.create_index('ix_gear_sources_source_lookup', 'gear_sources', ['source_name', 'source_record_id'], unique=False)
    op.create_table('oauth_providers',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_providers')),
    sa.UniqueConstraint('name', name=op.f('uq_oauth_providers_name'))
    )
    op.create_table('user_identities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['oauth_providers.id'], name=op.f('fk_user_identities_provider_id_oauth_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identities'))
    )
    op.create_index('ix_user_identities_provider_external', 'user_identities', ['provider_id', 'external_id'], unique=False)
    op.create_index('ix_user_identities_user_id', 'user_identities', ['user_id'], unique=False)
    op.create_table('gear_models',
    sa.Column('gear_id', sa.Uuid(), nullable=False),
    sa.Column('platform', webapp.adapters.persistence.models.base.EnumByValue(length=50), nullable=False),
    sa.Column('size', webapp.adapters.persistence.models.base.EnumByValue(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('download_status', webapp.adapters.persistence.models.base.EnumByValue(length=50), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['gear_id'], ['gear.id'], name=op.f('fk_gear_models_gear_id_gear'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gear_models'))
    )
    op.create_index('ix_gearmodel_gear_id', 'gear_models', ['gear_id'], unique=False)
    op.create_index('ix_gearmodel_platform', 'gear_models', ['platform'], unique=False)
    op.create_table('gear_tags',
    sa.Column('gear_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['gear_id'], ['gear.id'], name=op.f('fk_gear_tags_gear_id_gear'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_gear_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gear_id', 'tag_id', name=op.f('pk_gear_tags'))
    )
    op.create_table('audio_segments',
    sa.Column('shootout_chain_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('integrated_lufs', sa.Float(), nullable=False),
    sa.Column('peak_dbfs', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shootout_chain_id'], ['shootout_chains.id'], name=op.f('fk_audio_segments_shootout_chain_id_shootout_chains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_segments'))
    )
    op.create_index('ix_audio_segments_chain_id', 'audio_segments', ['shootout_chain_id'], unique=False)
    op.drop_index(op.f('ix_gear_source_name'), table_name='gear_source')
    op.drop_table('gear_source')
    op.drop_index(op.f('ix_t3k_tags_name'), table_name='t3k_tags')
    op.drop_table('t3k_tags')
    op.drop_index(op.f('ix_signal_chain_group_amps_group_id'), table_name='signal_chain_group_amps')
    op.drop_index(op.f('ix_signal_chain_group_amps_user_gear_id'), table_name='signal_chain_group_amps')
    op.drop_table('signal_chain_group_amps')
    op.drop_index(op.f('ix_user_gear_favorites'), table_name='user_gear', postgresql_where='(is_favorite = true)')
    op.drop_index(op.f('ix_user_gear_gear_model_id'), table_name='user_gear')
    op.drop_index(op.f('ix_user_gear_user_id'), table_name='user_gear')
    op.drop_table('user_gear')
    op.drop_index(op.f('ix_t3k_makes_name'), table_name='t3k_makes')
    op.drop_table('t3k_makes')
    op.drop_table('di_track_tags')
    op.drop_index(op.f('ix_user_notifications_created_at'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_user_unread'), table_name='user_notifications', postgresql_where='(is_read = false)')
    op.drop_table('user_notifications')
    op.drop_table('t3k_pack_tags')
    op.drop_index(op.f('ix_t3k_models_download_status'), table_name='t3k_models')
    op.drop_index(op.f('ix_t3k_models_model_size'), table_name='t3k_models')
    op.drop_index(op.f('ix_t3k_models_pack_id'), table_name='t3k_models')
    op.drop_index(op.f('ix_t3k_models_status'), table_name='t3k_models')
    op.drop_index(op.f('ix_t3k_models_t3k_model_id'), table_name='t3k_models')
    op.drop_index(op.f('uq_t3k_models_pack_model'), table_name='t3k_models')
    op.drop_table('t3k_models')
    op.drop_index(op.f('ix_error_reports_created_at'), table_name='error_reports')
    op.drop_index(op.f('ix_error_reports_error_code'), table_name='error_reports')
    op.drop_index(op.f('ix_error_reports_github_issue_null'), table_name='error_reports', postgresql_where='(github_issue_number IS NULL)')
    op.drop_index(op.f('ix_error_reports_github_issue_number'), table_name='error_reports')
    op.drop_index(op.f('ix_error_reports_request_id'), table_name='error_reports')
    op.drop_index(op.f('ix_error_reports_user_id'), table_name='error_reports')
    op.drop_table('error_reports')
    op.drop_index(op.f('ix_t3k_creators_t3k_creator_id'), table_name='t3k_creators')
    op.drop_index(op.f('ix_t3k_creators_username'), table_name='t3k_creators')
    op.drop_table('t3k_creators')
    op.drop_table('user_gear_tags')
    op.drop_index(op.f('ix_t3k_pack_images_pack_id'), table_name='t3k_pack_images')
    op.drop_table('t3k_pack_images')
    op.drop_index(op.f('ix_signal_chain_group_irs_group_id'), table_name='signal_chain_group_irs')
    op.drop_index(op.f('ix_signal_chain_group_irs_user_gear_id'), table_name='signal_chain_group_irs')
    op.drop_table('signal_chain_group_irs')
    op.drop_index(op.f('ix_t3k_pack_links_pack_id'), table_name='t3k_pack_links')
    op.drop_table('t3k_pack_links')
    op.drop_index(op.f('ix_gear_model_gear_id'), table_name='gear_model')
    op.drop_index(op.f('ix_gear_model_source_external_id'), table_name='gear_model')
    op.drop_index(op.f('ix_gear_model_source_lookup'), table_name='gear_model')
    op.drop_table('gear_model')
    op.drop_table('t3k_pack_makes')
    op.drop_index(op.f('ix_signal_chain_group_dis_di_track_id'), table_name='signal_chain_group_dis')
    op.drop_index(op.f('ix_signal_chain_group_dis_group_id'), table_name='signal_chain_group_dis')
    op.drop_table('signal_chain_group_dis')
    op.drop_index(op.f('ix_t3k_packs_created_at'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_creator_uuid'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_downloads'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_favorites_count'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_gear_type'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_not_deleted'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_platform'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_slug'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_sync_status'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_synced_at'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_t3k_pack_id'), table_name='t3k_packs')
    op.drop_index(op.f('ix_t3k_packs_title_fts'), table_name='t3k_packs', postgresql_using='gin')
    op.drop_index(op.f('ix_t3k_packs_type_platform'), table_name='t3k_packs')
    op.drop_table('t3k_packs')
    op.add_column('block_types', sa.Column('default_params', sa.JSON(), nullable=False))
    op.alter_column('block_types', 'category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('block_types', 'id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.drop_index(op.f('ix_block_types_category'), table_name='block_types')
    op.drop_index(op.f('ix_block_types_is_builtin'), table_name='block_types')
    op.create_unique_constraint(op.f('uq_block_types_name'), 'block_types', ['name'])
    op.drop_column('block_types', 'is_builtin')
    op.drop_column('block_types', 'implementation')
    op.drop_column('block_types', 'created_at')
    op.drop_column('block_types', 'updated_at')
    op.drop_column('block_types', 'parameters')
    op.add_column('di_tracks', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('di_tracks', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('di_tracks', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('di_tracks', sa.Column('pickup', sa.String(length=255), nullable=True))
    op.alter_column('di_tracks', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('di_tracks', 'checksum',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index(op.f('ix_di_tracks_checksum'), table_name='di_tracks')
    op.drop_index(op.f('ix_di_tracks_created'), table_name='di_tracks')
    op.drop_index(op.f('ix_di_tracks_is_public'), table_name='di_tracks')
    op.drop_index(op.f('ix_di_tracks_uploaded_by'), table_name='di_tracks')
    op.create_index('ix_di_tracks_user_id', 'di_tracks', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_di_tracks_uploaded_by_users'), 'di_tracks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_di_tracks_user_id_users'), 'di_tracks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('di_tracks', 'uploaded_by')
    op.drop_column('di_tracks', 'file_size_bytes')
    op.drop_column('di_tracks', 'is_system_track')
    op.drop_column('di_tracks', 'pickups')
    op.drop_column('di_tracks', 'title')
    op.drop_column('di_tracks', 'is_public')
    op.drop_column('di_tracks', 'tuning')
    op.drop_column('di_tracks', 'recording_interface')
    op.drop_column('di_tracks', 'waveform_data')
    op.drop_column('di_tracks', 'strings')
    op.add_column('gear', sa.Column('manufacturer', sa.String(length=100), nullable=True))
    op.add_column('gear', sa.Column('make_id', sa.Uuid(), nullable=True))
    op.add_column('gear', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('gear', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.alter_column('gear', 'name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('gear', 'gear_type',
               existing_type=postgresql.ENUM('amp', 'full_rig', 'pedal', 'outboard', 'ir', name='gear_type'),
               type_=webapp.adapters.persistence.models.base.EnumByValue(length=50),
               existing_nullable=False)
    op.alter_column('gear', 'source_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               nullable=True)
    op.drop_index(op.f('ix_gear_gear_type'), table_name='gear')
    op.drop_index(op.f('ix_gear_name'), table_name='gear')
    op.drop_index(op.f('ix_gear_platform'), table_name='gear')
    op.drop_index(op.f('ix_gear_type_platform'), table_name='gear')
    op.drop_constraint(op.f('uq_gear_source_external'), 'gear', type_='unique')
    op.create_index('ix_gear_is_public', 'gear', ['is_public'], unique=False)
    op.create_index('ix_gear_make_id', 'gear', ['make_id'], unique=False)
    op.create_index('ix_gear_type', 'gear', ['gear_type'], unique=False)
    op.drop_constraint(op.f('fk_gear_source_id_gear_source'), 'gear', type_='foreignkey')
    op.create_foreign_key(op.f('fk_gear_source_id_gear_sources'), 'gear', 'gear_sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_gear_make_id_gear_makes'), 'gear', 'gear_makes', ['make_id'], ['id'], ondelete='SET NULL')
    op.drop_column('gear', 'platform')
    op.drop_column('gear', 'creator')
    op.drop_column('gear', 'source_external_id')
    op.add_column('jobs', sa.Column('depends_on', sa.JSON(), nullable=False))
    op.add_column('jobs', sa.Column('attempt', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('entity_id', sa.Uuid(), nullable=True))
    op.alter_column('jobs', 'job_type',
               existing_type=postgresql.ENUM('shootout_process', 'model_download', 't3k_sync', 't3k_sync_full', 't3k_sync_incremental', name='job_type'),
               type_=webapp.adapters.persistence.models.base.EnumByValue(length=50),
               existing_nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('pending', 'queued', 'running', 'completed', 'failed', 'cancelled', 'dead_lettered', name='job_status'),
               type_=webapp.adapters.persistence.models.base.EnumByValue(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_reference'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_unique_active_shootout'), table_name='jobs', postgresql_where="((job_type = 'shootout_process'::job_type) AND (status = ANY (ARRAY['pending'::job_status, 'queued'::job_status, 'running'::job_status])))")
    op.drop_index(op.f('ix_jobs_unique_active_t3k_sync'), table_name='jobs', postgresql_where="((job_type = 't3k_sync'::job_type) AND (status = ANY (ARRAY['pending'::job_status, 'queued'::job_status, 'running'::job_status])))")
    op.create_index('ix_jobs_entity_id', 'jobs', ['entity_id'], unique=False)
    op.drop_column('jobs', 'retry_count')
    op.drop_column('jobs', 'reference_id')
    op.drop_column('jobs', 'reference_type')
    op.drop_column('jobs', 'config')
    op.drop_column('jobs', 'error_message')
    op.add_column('presets', sa.Column('signal_chain_block_id', sa.Uuid(), nullable=False))
    op.add_column('presets', sa.Column('params', sa.JSON(), nullable=False))
    op.alter_column('presets', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_presets_category'), table_name='presets')
    op.drop_index(op.f('ix_presets_is_factory'), table_name='presets')
    op.drop_index(op.f('ix_presets_is_public'), table_name='presets')
    op.drop_index(op.f('ix_presets_user_created'), table_name='presets')
    op.drop_index(op.f('ix_presets_user_id'), table_name='presets')
    op.create_index('ix_presets_block_id', 'presets', ['signal_chain_block_id'], unique=False)
    op.drop_constraint(op.f('fk_presets_user_id_users'), 'presets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_presets_signal_chain_block_id_signal_chain_blocks'), 'presets', 'signal_chain_blocks', ['signal_chain_block_id'], ['id'], ondelete='CASCADE')
    op.drop_column('presets', 'user_id')
    op.drop_column('presets', 'description')
    op.drop_column('presets', 'signal_chain')
    op.drop_column('presets', 'tags')
    op.drop_column('presets', 'created_at')
    op.drop_column('presets', 'is_public')
    op.drop_column('presets', 'version')
    op.drop_column('presets', 'genre')
    op.drop_column('presets', 'is_factory')
    op.drop_column('presets', 'updated_at')
    op.drop_column('presets', 'category')
    op.add_column('shootout_chains', sa.Column('signal_chain_id', sa.Uuid(), nullable=False))
    op.add_column('shootout_chains', sa.Column('label', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_shootout_chains_chain_id'), table_name='shootout_chains')
    op.drop_index(op.f('ix_shootout_chains_di_track_id'), table_name='shootout_chains')
    op.drop_index(op.f('uq_shootout_chains_di_chain'), table_name='shootout_chains')
    op.drop_index(op.f('uq_shootout_chains_position'), table_name='shootout_chains')
    op.create_index('ix_shootout_chains_position', 'shootout_chains', ['shootout_id', 'position'], unique=False)
    op.drop_constraint(op.f('fk_shootout_chains_chain_id_signal_chains'), 'shootout_chains', type_='foreignkey')
    op.drop_constraint(op.f('fk_shootout_chains_di_track_id'), 'shootout_chains', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shootout_chains_signal_chain_id_signal_chains'), 'shootout_chains', 'signal_chains', ['signal_chain_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shootout_chains', 'duration_ms')
    op.drop_column('shootout_chains', 'ai_eval_json')
    op.drop_column('shootout_chains', 'metrics_json')
    op.drop_column('shootout_chains', 'di_track_id')
    op.drop_column('shootout_chains', 'created_at')
    op.drop_column('shootout_chains', 'chain_id')
    op.drop_column('shootout_chains', 'updated_at')
    op.drop_column('shootout_chains', 'audio_path')
    op.add_column('shootouts', sa.Column('di_track_id', sa.Uuid(), nullable=False))
    op.add_column('shootouts', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('shootouts', sa.Column('video_path', sa.String(length=500), nullable=True))
    op.alter_column('shootouts', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=webapp.adapters.persistence.models.base.EnumByValue(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_shootouts_group_id'), table_name='shootouts')
    op.drop_index(op.f('ix_shootouts_user_created'), table_name='shootouts')
    op.drop_constraint(op.f('fk_shootouts_group_id'), 'shootouts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shootouts_di_track_id_di_tracks'), 'shootouts', 'di_tracks', ['di_track_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shootouts', 'name')
    op.drop_column('shootouts', 'master_audio_path')
    op.drop_column('shootouts', 'group_id')
    op.drop_column('shootouts', 'sample_rate')
    op.drop_column('shootouts', 'output_format')
    op.drop_column('shootouts', 'output_path')
    op.drop_column('shootouts', 'error_message')
    op.add_column('signal_chain_blocks', sa.Column('signal_chain_id', sa.Uuid(), nullable=False))
    op.add_column('signal_chain_blocks', sa.Column('gear_type', webapp.adapters.persistence.models.base.EnumByValue(length=50), nullable=False))
    op.drop_index(op.f('ix_signal_chain_blocks_user_gear_id'), table_name='signal_chain_blocks')
    op.drop_index(op.f('uq_signal_chain_blocks_chain_position'), table_name='signal_chain_blocks')
    op.drop_index(op.f('ix_signal_chain_blocks_chain_id'), table_name='signal_chain_blocks')
    op.create_index('ix_signal_chain_blocks_chain_id', 'signal_chain_blocks', ['signal_chain_id'], unique=False)
    op.create_index('ix_signal_chain_blocks_position', 'signal_chain_blocks', ['signal_chain_id', 'position'], unique=False)
    op.drop_constraint(op.f('fk_signal_chain_blocks_chain_id_signal_chains'), 'signal_chain_blocks', type_='foreignkey')
    op.drop_constraint(op.f('fk_signal_chain_blocks_user_gear_id_user_gear'), 'signal_chain_blocks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_signal_chain_blocks_signal_chain_id_signal_chains'), 'signal_chain_blocks', 'signal_chains', ['signal_chain_id'], ['id'], ondelete='CASCADE')
    op.drop_column('signal_chain_blocks', 'created_at')
    op.drop_column('signal_chain_blocks', 'updated_at')
    op.drop_column('signal_chain_blocks', 'chain_id')
    op.add_column('signal_chain_groups', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('signal_chain_groups', sa.Column('base_chain_id', sa.Uuid(), nullable=True))
    op.add_column('signal_chain_groups', sa.Column('slot_positions', sa.JSON(), nullable=False))
    op.add_column('signal_chain_groups', sa.Column('gear_options', sa.JSON(), nullable=False))
    op.add_column('signal_chain_groups', sa.Column('include_null', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_signal_chain_groups_user_created'), table_name='signal_chain_groups')
    op.create_foreign_key(op.f('fk_signal_chain_groups_base_chain_id_signal_chains'), 'signal_chain_groups', 'signal_chains', ['base_chain_id'], ['id'], ondelete='SET NULL')
    op.drop_column('signal_chain_groups', 'platform')
    op.alter_column('signal_chains', 'platform',
               existing_type=sa.VARCHAR(length=20),
               type_=webapp.adapters.persistence.models.base.EnumByValue(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'nam'::character varying"))
    op.drop_index(op.f('ix_signal_chains_group_id'), table_name='signal_chains')
    op.drop_index(op.f('ix_signal_chains_user_created'), table_name='signal_chains')
    op.drop_constraint(op.f('fk_signal_chains_group_id_signal_chain_groups'), 'signal_chains', type_='foreignkey')
    op.drop_column('signal_chains', 'is_valid')
    op.drop_column('signal_chains', 'is_complete')
    op.drop_column('signal_chains', 'group_id')
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_column('tags', 'created_at')
    op.drop_column('tags', 'updated_at')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_tone3000_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'tone3000_id')
    op.drop_column('users', 'token_expires_at')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')

    # Seed data
    from uuid import uuid4

    # Seed OAuthProvider
    oauth_providers = [
        {
            'id': uuid4(),
            'name': 'tone3000',
            'enabled': True,
        },
    ]
    op.bulk_insert(
        sa.table('oauth_providers',
            sa.column('id', sa.Uuid()),
            sa.column('name', sa.String()),
            sa.column('enabled', sa.Boolean()),
        ),
        oauth_providers
    )

    # Seed BlockType - Built-in processor definitions
    block_types = [
        {
            'id': uuid4(),
            'name': 'Gain',
            'category': 'gain',
            'default_params': {},
        },
        {
            'id': uuid4(),
            'name': 'Compressor',
            'category': 'dynamics',
            'default_params': {},
        },
        {
            'id': uuid4(),
            'name': 'EQ',
            'category': 'eq',
            'default_params': {},
        },
        {
            'id': uuid4(),
            'name': 'Chorus',
            'category': 'modulation',
            'default_params': {},
        },
        {
            'id': uuid4(),
            'name': 'Delay',
            'category': 'delay',
            'default_params': {},
        },
        {
            'id': uuid4(),
            'name': 'Reverb',
            'category': 'reverb',
            'default_params': {},
        },
    ]
    op.bulk_insert(
        sa.table('block_types',
            sa.column('id', sa.Uuid()),
            sa.column('name', sa.String()),
            sa.column('category', sa.String()),
            sa.column('default_params', postgresql.JSONB()),
        ),
        block_types
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(length=4000), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=4000), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tone3000_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_tone3000_id'), 'users', ['tone3000_id'], unique=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    op.drop_column('users', 'email')
    op.add_column('tags', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tags', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.alter_column('tags', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('signal_chains', sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('signal_chains', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('signal_chains', sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_signal_chains_group_id_signal_chain_groups'), 'signal_chains', 'signal_chain_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_signal_chains_user_created'), 'signal_chains', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_signal_chains_group_id'), 'signal_chains', ['group_id'], unique=False)
    op.alter_column('signal_chains', 'platform',
               existing_type=webapp.adapters.persistence.models.base.EnumByValue(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'nam'::character varying"))
    op.add_column('signal_chain_groups', sa.Column('platform', sa.VARCHAR(length=20), server_default=sa.text("'nam'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_signal_chain_groups_base_chain_id_signal_chains'), 'signal_chain_groups', type_='foreignkey')
    op.create_index(op.f('ix_signal_chain_groups_user_created'), 'signal_chain_groups', ['user_id', 'created_at'], unique=False)
    op.drop_column('signal_chain_groups', 'include_null')
    op.drop_column('signal_chain_groups', 'gear_options')
    op.drop_column('signal_chain_groups', 'slot_positions')
    op.drop_column('signal_chain_groups', 'base_chain_id')
    op.drop_column('signal_chain_groups', 'description')
    op.add_column('signal_chain_blocks', sa.Column('chain_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('signal_chain_blocks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('signal_chain_blocks', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_signal_chain_blocks_signal_chain_id_signal_chains'), 'signal_chain_blocks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_signal_chain_blocks_user_gear_id_user_gear'), 'signal_chain_blocks', 'user_gear', ['user_gear_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_signal_chain_blocks_chain_id_signal_chains'), 'signal_chain_blocks', 'signal_chains', ['chain_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_signal_chain_blocks_position', table_name='signal_chain_blocks')
    op.drop_index('ix_signal_chain_blocks_chain_id', table_name='signal_chain_blocks')
    op.create_index(op.f('ix_signal_chain_blocks_chain_id'), 'signal_chain_blocks', ['chain_id'], unique=False)
    op.create_index(op.f('uq_signal_chain_blocks_chain_position'), 'signal_chain_blocks', ['chain_id', 'position'], unique=True)
    op.create_index(op.f('ix_signal_chain_blocks_user_gear_id'), 'signal_chain_blocks', ['user_gear_id'], unique=False)
    op.drop_column('signal_chain_blocks', 'gear_type')
    op.drop_column('signal_chain_blocks', 'signal_chain_id')
    op.add_column('shootouts', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('shootouts', sa.Column('output_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('shootouts', sa.Column('output_format', sa.VARCHAR(length=20), server_default=sa.text("'wav'::character varying"), autoincrement=False, nullable=False))
    op.add_column('shootouts', sa.Column('sample_rate', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shootouts', sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('shootouts', sa.Column('master_audio_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('shootouts', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_shootouts_di_track_id_di_tracks'), 'shootouts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shootouts_group_id'), 'shootouts', 'signal_chain_groups', ['group_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_shootouts_user_created'), 'shootouts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_shootouts_group_id'), 'shootouts', ['group_id'], unique=False)
    op.alter_column('shootouts', 'status',
               existing_type=webapp.adapters.persistence.models.base.EnumByValue(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('shootouts', 'video_path')
    op.drop_column('shootouts', 'title')
    op.drop_column('shootouts', 'di_track_id')
    op.add_column('shootout_chains', sa.Column('audio_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('shootout_chains', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('shootout_chains', sa.Column('chain_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('shootout_chains', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('shootout_chains', sa.Column('di_track_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('shootout_chains', sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('shootout_chains', sa.Column('ai_eval_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('shootout_chains', sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_shootout_chains_signal_chain_id_signal_chains'), 'shootout_chains', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shootout_chains_di_track_id'), 'shootout_chains', 'di_tracks', ['di_track_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_shootout_chains_chain_id_signal_chains'), 'shootout_chains', 'signal_chains', ['chain_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_shootout_chains_position', table_name='shootout_chains')
    op.create_index(op.f('uq_shootout_chains_position'), 'shootout_chains', ['shootout_id', 'position'], unique=True)
    op.create_index(op.f('uq_shootout_chains_di_chain'), 'shootout_chains', ['shootout_id', 'di_track_id', 'chain_id'], unique=True)
    op.create_index(op.f('ix_shootout_chains_di_track_id'), 'shootout_chains', ['di_track_id'], unique=False)
    op.create_index(op.f('ix_shootout_chains_chain_id'), 'shootout_chains', ['chain_id'], unique=False)
    op.drop_column('shootout_chains', 'label')
    op.drop_column('shootout_chains', 'signal_chain_id')
    op.add_column('presets', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('presets', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('presets', sa.Column('is_factory', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('presets', sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('presets', sa.Column('version', sa.VARCHAR(length=20), server_default=sa.text("'1.0'::character varying"), autoincrement=False, nullable=False))
    op.add_column('presets', sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('presets', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('presets', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR(length=50)), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.add_column('presets', sa.Column('signal_chain', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"blocks": [], "sample_rate": 48000}\'::jsonb'), autoincrement=False, nullable=False))
    op.add_column('presets', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('presets', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_presets_signal_chain_block_id_signal_chain_blocks'), 'presets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_presets_user_id_users'), 'presets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_presets_block_id', table_name='presets')
    op.create_index(op.f('ix_presets_user_id'), 'presets', ['user_id'], unique=False)
    op.create_index(op.f('ix_presets_user_created'), 'presets', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_presets_is_public'), 'presets', ['is_public'], unique=False)
    op.create_index(op.f('ix_presets_is_factory'), 'presets', ['is_factory'], unique=False)
    op.create_index(op.f('ix_presets_category'), 'presets', ['category'], unique=False)
    op.alter_column('presets', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('presets', 'params')
    op.drop_column('presets', 'signal_chain_block_id')
    op.add_column('jobs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('ix_jobs_entity_id', table_name='jobs')
    op.create_index(op.f('ix_jobs_unique_active_t3k_sync'), 'jobs', ['job_type'], unique=True, postgresql_where="((job_type = 't3k_sync'::job_type) AND (status = ANY (ARRAY['pending'::job_status, 'queued'::job_status, 'running'::job_status])))")
    op.create_index(op.f('ix_jobs_unique_active_shootout'), 'jobs', ['job_type'], unique=True, postgresql_where="((job_type = 'shootout_process'::job_type) AND (status = ANY (ARRAY['pending'::job_status, 'queued'::job_status, 'running'::job_status])))")
    op.create_index(op.f('ix_jobs_reference'), 'jobs', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.alter_column('jobs', 'status',
               existing_type=webapp.adapters.persistence.models.base.EnumByValue(length=50),
               type_=postgresql.ENUM('pending', 'queued', 'running', 'completed', 'failed', 'cancelled', 'dead_lettered', name='job_status'),
               existing_nullable=False)
    op.alter_column('jobs', 'job_type',
               existing_type=webapp.adapters.persistence.models.base.EnumByValue(length=50),
               type_=postgresql.ENUM('shootout_process', 'model_download', 't3k_sync', 't3k_sync_full', 't3k_sync_incremental', name='job_type'),
               existing_nullable=False)
    op.drop_column('jobs', 'entity_id')
    op.drop_column('jobs', 'error')
    op.drop_column('jobs', 'max_attempts')
    op.drop_column('jobs', 'attempt')
    op.drop_column('jobs', 'depends_on')
    op.add_column('gear', sa.Column('source_external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('gear', sa.Column('creator', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('gear', sa.Column('platform', postgresql.ENUM('nam', 'ir', 'aida_x', 'aa_snapshot', 'proteus', name='gear_platform'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_gear_make_id_gear_makes'), 'gear', type_='foreignkey')
    op.drop_constraint(op.f('fk_gear_source_id_gear_sources'), 'gear', type_='foreignkey')
    op.create_foreign_key(op.f('fk_gear_source_id_gear_source'), 'gear', 'gear_source', ['source_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_gear_type', table_name='gear')
    op.drop_index('ix_gear_make_id', table_name='gear')
    op.drop_index('ix_gear_is_public', table_name='gear')
    op.create_unique_constraint(op.f('uq_gear_source_external'), 'gear', ['source_id', 'source_external_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_gear_type_platform'), 'gear', ['gear_type', 'platform'], unique=False)
    op.create_index(op.f('ix_gear_platform'), 'gear', ['platform'], unique=False)
    op.create_index(op.f('ix_gear_name'), 'gear', ['name'], unique=False)
    op.create_index(op.f('ix_gear_gear_type'), 'gear', ['gear_type'], unique=False)
    op.alter_column('gear', 'source_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('gear', 'gear_type',
               existing_type=webapp.adapters.persistence.models.base.EnumByValue(length=50),
               type_=postgresql.ENUM('amp', 'full_rig', 'pedal', 'outboard', 'ir', name='gear_type'),
               existing_nullable=False)
    op.alter_column('gear', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('gear', 'is_public')
    op.drop_column('gear', 'thumbnail_url')
    op.drop_column('gear', 'make_id')
    op.drop_column('gear', 'manufacturer')
    op.add_column('di_tracks', sa.Column('strings', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('di_tracks', sa.Column('waveform_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('di_tracks', sa.Column('recording_interface', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('di_tracks', sa.Column('tuning', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('di_tracks', sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('di_tracks', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('di_tracks', sa.Column('pickups', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('di_tracks', sa.Column('is_system_track', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('di_tracks', sa.Column('file_size_bytes', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('di_tracks', sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_di_tracks_user_id_users'), 'di_tracks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_di_tracks_uploaded_by_users'), 'di_tracks', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_di_tracks_user_id', table_name='di_tracks')
    op.create_index(op.f('ix_di_tracks_uploaded_by'), 'di_tracks', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_di_tracks_is_public'), 'di_tracks', ['is_public'], unique=False)
    op.create_index(op.f('ix_di_tracks_created'), 'di_tracks', ['created_at'], unique=False)
    op.create_index(op.f('ix_di_tracks_checksum'), 'di_tracks', ['checksum'], unique=False)
    op.alter_column('di_tracks', 'checksum',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('di_tracks', 'file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_column('di_tracks', 'pickup')
    op.drop_column('di_tracks', 'original_filename')
    op.drop_column('di_tracks', 'name')
    op.drop_column('di_tracks', 'user_id')
    op.add_column('block_types', sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('block_types', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('block_types', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('block_types', sa.Column('implementation', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('block_types', sa.Column('is_builtin', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_block_types_name'), 'block_types', type_='unique')
    op.create_index(op.f('ix_block_types_is_builtin'), 'block_types', ['is_builtin'], unique=False)
    op.create_index(op.f('ix_block_types_category'), 'block_types', ['category'], unique=False)
    op.alter_column('block_types', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('block_types', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('block_types', 'default_params')
    op.create_table('t3k_packs',
    sa.Column('t3k_pack_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gear_type', postgresql.ENUM('amp', 'full-rig', 'pedal', 'outboard', 'ir', name='t3k_gear_type'), autoincrement=False, nullable=False),
    sa.Column('platform', postgresql.ENUM('nam', 'ir', 'aida-x', 'aa-snapshot', 'proteus', name='t3k_platform'), autoincrement=False, nullable=False),
    sa.Column('license', postgresql.ENUM('cc-by', 'cc-by-sa', 'cc-by-nc', 'cc-by-nc-sa', 'cc-by-nd', 'cc-by-nc-nd', 'cc0', 'custom', 't3k', 'cco', name='t3k_license'), autoincrement=False, nullable=False),
    sa.Column('downloads_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('favorites_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('models_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('t3k_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('creator_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('t3k_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('t3k_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=550), autoincrement=False, nullable=False),
    sa.Column('sync_status', postgresql.ENUM('syncing', 'complete', 'partial', name='t3k_pack_sync_status'), server_default=sa.text("'syncing'::t3k_pack_sync_status"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_uuid'], ['t3k_creators.id'], name=op.f('fk_t3k_packs_creator_uuid'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t3k_packs')),
    sa.UniqueConstraint('slug', name=op.f('uq_t3k_packs_slug'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_t3k_packs_type_platform'), 't3k_packs', ['gear_type', 'platform'], unique=False)
    op.create_index(op.f('ix_t3k_packs_title_fts'), 't3k_packs', [sa.literal_column("to_tsvector('english'::regconfig, title::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_t3k_packs_t3k_pack_id'), 't3k_packs', ['t3k_pack_id'], unique=True)
    op.create_index(op.f('ix_t3k_packs_synced_at'), 't3k_packs', ['synced_at'], unique=False)
    op.create_index(op.f('ix_t3k_packs_sync_status'), 't3k_packs', ['sync_status'], unique=False)
    op.create_index(op.f('ix_t3k_packs_slug'), 't3k_packs', ['slug'], unique=False)
    op.create_index(op.f('ix_t3k_packs_platform'), 't3k_packs', ['platform'], unique=False)
    op.create_index(op.f('ix_t3k_packs_not_deleted'), 't3k_packs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_t3k_packs_gear_type'), 't3k_packs', ['gear_type'], unique=False)
    op.create_index(op.f('ix_t3k_packs_favorites_count'), 't3k_packs', ['favorites_count'], unique=False)
    op.create_index(op.f('ix_t3k_packs_downloads'), 't3k_packs', ['downloads_count'], unique=False)
    op.create_index(op.f('ix_t3k_packs_creator_uuid'), 't3k_packs', ['creator_uuid'], unique=False)
    op.create_index(op.f('ix_t3k_packs_created_at'), 't3k_packs', ['t3k_created_at'], unique=False)
    op.create_table('signal_chain_group_dis',
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('di_track_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['di_track_id'], ['di_tracks.id'], name=op.f('fk_signal_chain_group_dis_di_track_id_di_tracks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['signal_chain_groups.id'], name=op.f('fk_signal_chain_group_dis_group_id_signal_chain_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_chain_group_dis')),
    sa.UniqueConstraint('group_id', 'position', name=op.f('uq_signal_chain_group_dis_position'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_signal_chain_group_dis_group_id'), 'signal_chain_group_dis', ['group_id'], unique=False)
    op.create_index(op.f('ix_signal_chain_group_dis_di_track_id'), 'signal_chain_group_dis', ['di_track_id'], unique=False)
    op.create_table('t3k_pack_makes',
    sa.Column('pack_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('make_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['t3k_makes.id'], name=op.f('fk_t3k_pack_makes_make_id_t3k_makes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['t3k_packs.id'], name=op.f('fk_t3k_pack_makes_pack_id_t3k_packs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pack_id', 'make_id', name=op.f('pk_t3k_pack_makes'))
    )
    op.create_table('gear_model',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('gear_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('download_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gear_id'], ['gear.id'], name=op.f('fk_gear_model_gear_id_gear'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['gear_source.id'], name=op.f('fk_gear_model_source_id_gear_source'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gear_model')),
    sa.UniqueConstraint('source_id', 'source_external_id', name=op.f('uq_gear_model_source_external'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_gear_model_source_lookup'), 'gear_model', ['source_id', 'source_external_id'], unique=False)
    op.create_index(op.f('ix_gear_model_source_external_id'), 'gear_model', ['source_external_id'], unique=False)
    op.create_index(op.f('ix_gear_model_gear_id'), 'gear_model', ['gear_id'], unique=False)
    op.create_table('t3k_pack_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pack_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('link_type', postgresql.ENUM('external', 'video', name='t3k_link_type'), server_default=sa.text("'external'::t3k_link_type"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['t3k_packs.id'], name=op.f('fk_t3k_pack_links_pack_id_t3k_packs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t3k_pack_links'))
    )
    op.create_index(op.f('ix_t3k_pack_links_pack_id'), 't3k_pack_links', ['pack_id'], unique=False)
    op.create_table('signal_chain_group_irs',
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_gear_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['signal_chain_groups.id'], name=op.f('fk_signal_chain_group_irs_group_id_signal_chain_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_gear_id'], ['user_gear.id'], name=op.f('fk_signal_chain_group_irs_user_gear_id_user_gear'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_chain_group_irs')),
    sa.UniqueConstraint('group_id', 'position', name=op.f('uq_signal_chain_group_irs_position'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_signal_chain_group_irs_user_gear_id'), 'signal_chain_group_irs', ['user_gear_id'], unique=False)
    op.create_index(op.f('ix_signal_chain_group_irs_group_id'), 'signal_chain_group_irs', ['group_id'], unique=False)
    op.create_table('t3k_pack_images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pack_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('position', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['t3k_packs.id'], name=op.f('fk_t3k_pack_images_pack_id_t3k_packs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t3k_pack_images'))
    )
    op.create_index(op.f('ix_t3k_pack_images_pack_id'), 't3k_pack_images', ['pack_id'], unique=False)
    op.create_table('user_gear_tags',
    sa.Column('user_gear_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_user_gear_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_gear_id'], ['user_gear.id'], name=op.f('fk_user_gear_tags_user_gear_id_user_gear'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_gear_id', 'tag_id', name=op.f('pk_user_gear_tags'))
    )
    op.create_table('t3k_creators',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('t3k_creator_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t3k_creators')),
    sa.UniqueConstraint('t3k_creator_id', name=op.f('uq_t3k_creators_t3k_creator_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_t3k_creators_username'), 't3k_creators', ['username'], unique=False)
    op.create_index(op.f('ix_t3k_creators_t3k_creator_id'), 't3k_creators', ['t3k_creator_id'], unique=False)
    op.create_table('error_reports',
    sa.Column('error_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Error code in CATEGORY_NNN format (e.g., INT_001, VAL_002)'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=False, comment='Sanitized error message displayed to user'),
    sa.Column('page_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False, comment='URL where the error occurred'),
    sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Request ID for log correlation'),
    sa.Column('user_comment', sa.TEXT(), autoincrement=False, nullable=True, comment="User's description of what they were doing"),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True, comment='User who submitted the report (null for anonymous)'),
    sa.Column('github_issue_number', sa.INTEGER(), autoincrement=False, nullable=True, comment='GitHub issue number created for this report'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_error_reports_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_reports'))
    )
    op.create_index(op.f('ix_error_reports_user_id'), 'error_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_error_reports_request_id'), 'error_reports', ['request_id'], unique=False)
    op.create_index(op.f('ix_error_reports_github_issue_number'), 'error_reports', ['github_issue_number'], unique=False)
    op.create_index(op.f('ix_error_reports_github_issue_null'), 'error_reports', ['github_issue_number'], unique=False, postgresql_where='(github_issue_number IS NULL)')
    op.create_index(op.f('ix_error_reports_error_code'), 'error_reports', ['error_code'], unique=False)
    op.create_index(op.f('ix_error_reports_created_at'), 'error_reports', ['created_at'], unique=False)
    op.create_table('t3k_models',
    sa.Column('pack_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('t3k_model_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('model_size', postgresql.ENUM('STANDARD', 'LITE', 'FEATHER', 'NANO', 'standard', 'lite', 'feather', 'nano', 'custom', name='t3k_model_size'), autoincrement=False, nullable=False),
    sa.Column('download_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('file_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('local_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('download_status', postgresql.ENUM('pending', 'queued', 'downloading', 'completed', 'failed', name='download_status'), autoincrement=False, nullable=False),
    sa.Column('download_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['t3k_packs.id'], name=op.f('fk_t3k_models_pack_id_t3k_packs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t3k_models'))
    )
    op.create_index(op.f('uq_t3k_models_pack_model'), 't3k_models', ['pack_id', 't3k_model_id'], unique=True)
    op.create_index(op.f('ix_t3k_models_t3k_model_id'), 't3k_models', ['t3k_model_id'], unique=False)
    op.create_index(op.f('ix_t3k_models_status'), 't3k_models', ['download_status'], unique=False)
    op.create_index(op.f('ix_t3k_models_pack_id'), 't3k_models', ['pack_id'], unique=False)
    op.create_index(op.f('ix_t3k_models_model_size'), 't3k_models', ['model_size'], unique=False)
    op.create_index(op.f('ix_t3k_models_download_status'), 't3k_models', ['download_status'], unique=False)
    op.create_table('t3k_pack_tags',
    sa.Column('pack_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['t3k_packs.id'], name=op.f('fk_t3k_pack_tags_pack_id_t3k_packs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['t3k_tags.id'], name=op.f('fk_t3k_pack_tags_tag_id_t3k_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pack_id', 'tag_id', name=op.f('pk_t3k_pack_tags'))
    )
    op.create_table('user_notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notifications'))
    )
    op.create_index(op.f('ix_user_notifications_user_unread'), 'user_notifications', ['user_id', 'is_read'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_created_at'), 'user_notifications', ['created_at'], unique=False)
    op.create_table('di_track_tags',
    sa.Column('di_track_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['di_track_id'], ['di_tracks.id'], name=op.f('fk_di_track_tags_di_track_id_di_tracks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_di_track_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('di_track_id', 'tag_id', name=op.f('pk_di_track_tags'))
    )
    op.create_table('t3k_makes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t3k_makes')),
    sa.UniqueConstraint('name', name=op.f('uq_t3k_makes_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_t3k_makes_name'), 't3k_makes', ['name'], unique=False)
    op.create_table('user_gear',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('gear_model_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gear_model_id'], ['gear_model.id'], name=op.f('fk_user_gear_gear_model_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_gear_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_gear')),
    sa.UniqueConstraint('user_id', 'gear_model_id', name=op.f('uq_user_gear_user_gear_model'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_gear_user_id'), 'user_gear', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_gear_gear_model_id'), 'user_gear', ['gear_model_id'], unique=False)
    op.create_index(op.f('ix_user_gear_favorites'), 'user_gear', ['user_id', 'is_favorite'], unique=False, postgresql_where='(is_favorite = true)')
    op.create_table('signal_chain_group_amps',
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_gear_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['signal_chain_groups.id'], name=op.f('fk_signal_chain_group_amps_group_id_signal_chain_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_gear_id'], ['user_gear.id'], name=op.f('fk_signal_chain_group_amps_user_gear_id_user_gear'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_chain_group_amps')),
    sa.UniqueConstraint('group_id', 'position', name=op.f('uq_signal_chain_group_amps_position'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_signal_chain_group_amps_user_gear_id'), 'signal_chain_group_amps', ['user_gear_id'], unique=False)
    op.create_index(op.f('ix_signal_chain_group_amps_group_id'), 'signal_chain_group_amps', ['group_id'], unique=False)
    op.create_table('t3k_tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t3k_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_t3k_tags_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_t3k_tags_name'), 't3k_tags', ['name'], unique=False)
    op.create_table('gear_source',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gear_source')),
    sa.UniqueConstraint('name', name=op.f('uq_gear_source_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_gear_source_name'), 'gear_source', ['name'], unique=True)
    op.drop_index('ix_audio_segments_chain_id', table_name='audio_segments')
    op.drop_table('audio_segments')
    op.drop_table('gear_tags')
    op.drop_index('ix_gearmodel_platform', table_name='gear_models')
    op.drop_index('ix_gearmodel_gear_id', table_name='gear_models')
    op.drop_table('gear_models')
    op.drop_index('ix_user_identities_user_id', table_name='user_identities')
    op.drop_index('ix_user_identities_provider_external', table_name='user_identities')
    op.drop_table('user_identities')
    # Delete seed data (no need - tables are being dropped)
    # Seed data will be removed when tables are dropped

    op.drop_table('oauth_providers')
    op.drop_index('ix_gear_sources_source_lookup', table_name='gear_sources')
    op.drop_table('gear_sources')
    op.drop_table('gear_makes')
    # ### end Alembic commands ###
