"""Resource allocation and configuration file generation."""

from datetime import UTC, datetime
from pathlib import Path

import yaml  # type: ignore[import-untyped]

from .config import (
    PortConfig,
    VolumeConfig,
)
from .registry import Worktree


def generate_env_local(worktree: Worktree, output_path: Path) -> None:
    """Generate .env.local file for a worktree.

    Args:
        worktree: Worktree configuration
        output_path: Path to write .env.local
    """
    content = f"""# .env.local - Worktree-specific environment overrides
# Auto-generated by worktree.py - DO NOT EDIT MANUALLY
# Worktree: {worktree.worktree_name}
# Branch: {worktree.branch}
# Generated: {datetime.now(UTC).isoformat()}

# Docker Compose project name (isolates containers/networks)
COMPOSE_PROJECT_NAME={worktree.compose_project}

# Port overrides (external ports)
# FRONTEND_PORT not exposed - access via nginx at port {worktree.ports.nginx}
WEBAPP_PORT={worktree.ports.webapp}
DB_PORT={worktree.ports.db}
REDIS_PORT={worktree.ports.redis}

# API URL for frontend (must use external webapp port)
PUBLIC_URL=http://localhost:{worktree.ports.webapp}

# Volume names (isolated per worktree)
POSTGRES_VOLUME={worktree.volumes.postgres}
REDIS_VOLUME={worktree.volumes.redis}
UPLOADS_VOLUME={worktree.volumes.uploads}
"""
    output_path.write_text(content)


def generate_compose_override(worktree: Worktree, output_path: Path) -> None:
    """Generate docker-compose.override.yml for a worktree.

    Args:
        worktree: Worktree configuration
        output_path: Path to write docker-compose.override.yml
    """
    ports = worktree.ports
    volumes = worktree.volumes

    override = {
        # Header comment
        "x-generated": {
            "worktree": worktree.worktree_name,
            "branch": worktree.branch,
            "compose_project": worktree.compose_project,
            "generated_at": datetime.now(UTC).isoformat(),
        },
        "services": {
            "webapp": {
                "container_name": f"{worktree.compose_project}-webapp",
                "ports": [f"127.0.0.1:{ports.webapp}:8000"],
                "volumes": [
                    "./webapp:/app",
                    "./pipeline:/pipeline:ro",
                    f"{volumes.uploads}:/data/uploads",
                ],
                "environment": [
                    f"PUBLIC_URL=http://localhost:{ports.webapp}",
                ],
            },
            "astro": {
                "container_name": f"{worktree.compose_project}-astro",
                # No port exposed - access via nginx at port {ports.nginx}
                "environment": [
                    f"PUBLIC_URL=http://localhost:{ports.nginx}",
                ],
            },
            "worker": {
                "container_name": f"{worktree.compose_project}-worker",
                "volumes": [
                    "./backend:/app",
                    "./pipeline:/pipeline:ro",
                ],
            },
            "db": {
                "container_name": f"{worktree.compose_project}-db",
                "ports": [f"127.0.0.1:{ports.db}:5432"],
                "volumes": [f"{volumes.postgres}:/var/lib/postgresql/data"],
            },
            "redis": {
                "container_name": f"{worktree.compose_project}-redis",
                "ports": [f"127.0.0.1:{ports.redis}:6379"],
                "volumes": [f"{volumes.redis}:/data"],
            },
        },
        "volumes": {
            volumes.postgres: None,
            volumes.redis: None,
            volumes.uploads: None,
        },
    }

    # Write with comment header
    header = f"""# docker-compose.override.yml
# Auto-generated by worktree.py - DO NOT EDIT MANUALLY
# Worktree: {worktree.worktree_name}
# Branch: {worktree.branch}
# Generated: {datetime.now(UTC).isoformat()}
#
# This file overrides docker-compose.yml with worktree-specific ports and volumes.

"""
    yaml_content = yaml.dump(override, default_flow_style=False, sort_keys=False)
    output_path.write_text(header + yaml_content)


def check_ports_available(ports: PortConfig) -> dict[str, bool]:
    """Check if ports are available for binding.

    Args:
        ports: PortConfig to check

    Returns:
        Dict mapping port names to availability (True = available)
    """
    import socket

    results = {}

    # Core services (frontend not exposed - Docker internal only)
    core_ports = [
        ("nginx", ports.nginx),  # User-facing entry point
        ("webapp", ports.webapp),
        ("db", ports.db),
        ("redis", ports.redis),
        ("cloudbeaver", ports.cloudbeaver),
    ]

    # Observability services (optional, profile-based)
    observability_ports = [
        ("grafana", ports.grafana),
        ("prometheus", ports.prometheus),
        ("loki", ports.loki),
        ("tempo", ports.tempo),
        ("otlp_grpc", ports.otlp_grpc),
        ("otlp_http", ports.otlp_http),
        ("alloy", ports.alloy),
    ]

    for name, port in core_ports + observability_ports:
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.bind(("127.0.0.1", port))
                results[name] = True
        except OSError:
            results[name] = False

    return results


def format_ports_display(ports: PortConfig) -> str:
    """Format ports for display.

    Args:
        ports: PortConfig to format

    Returns:
        Formatted string like "nginx:9000/be:8000/db:5432/redis:6379/cb:8978"
    """
    return (
        f"nginx:{ports.nginx}/wa:{ports.webapp}/"
        f"db:{ports.db}/redis:{ports.redis}/cb:{ports.cloudbeaver}"
    )


def format_volumes_display(volumes: VolumeConfig) -> str:
    """Format volumes for display.

    Args:
        volumes: VolumeConfig to format

    Returns:
        Formatted string with volume names
    """
    return (
        f"pg:{volumes.postgres}, redis:{volumes.redis}, "
        f"uploads:{volumes.uploads}, cb:{volumes.cloudbeaver}"
    )
