"""Resource allocation and configuration file generation."""

from datetime import datetime, timezone
from pathlib import Path

import yaml

from .config import (
    PortConfig,
    VolumeConfig,
    get_seed_path,
    settings,
)
from .registry import Worktree


def generate_env_local(worktree: Worktree, output_path: Path) -> None:
    """Generate .env.local file for a worktree.

    Args:
        worktree: Worktree configuration
        output_path: Path to write .env.local
    """
    content = f"""# .env.local - Worktree-specific environment overrides
# Auto-generated by worktree.py - DO NOT EDIT MANUALLY
# Worktree: {worktree.worktree_name}
# Branch: {worktree.branch}
# Generated: {datetime.now(timezone.utc).isoformat()}

# Docker Compose project name (isolates containers/networks)
COMPOSE_PROJECT_NAME={worktree.compose_project}

# Port overrides (external ports)
FRONTEND_PORT={worktree.ports.frontend}
BACKEND_PORT={worktree.ports.backend}
DB_PORT={worktree.ports.db}
REDIS_PORT={worktree.ports.redis}

# API URL for frontend (must use external backend port)
PUBLIC_API_URL=http://localhost:{worktree.ports.backend}

# Volume names (isolated per worktree)
POSTGRES_VOLUME={worktree.volumes.postgres}
REDIS_VOLUME={worktree.volumes.redis}
UPLOADS_VOLUME={worktree.volumes.uploads}

# Model cache (shared, read-only in containers)
MODEL_CACHE_VOLUME={settings.shared_model_cache_volume}
"""
    output_path.write_text(content)


def generate_compose_override(worktree: Worktree, output_path: Path) -> None:
    """Generate docker-compose.override.yml for a worktree.

    Args:
        worktree: Worktree configuration
        output_path: Path to write docker-compose.override.yml
    """
    ports = worktree.ports
    volumes = worktree.volumes

    override = {
        # Header comment
        "x-generated": {
            "worktree": worktree.worktree_name,
            "branch": worktree.branch,
            "compose_project": worktree.compose_project,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        },
        "services": {
            "backend": {
                "container_name": f"{worktree.compose_project}-backend",
                "ports": [f"127.0.0.1:{ports.backend}:8000"],
                "volumes": [
                    "./backend:/app",
                    "./pipeline:/pipeline:ro",
                    f"{settings.shared_model_cache_volume}:/data/models/cache:ro",
                    f"{volumes.uploads}:/data/uploads",
                ],
                "environment": [
                    f"PUBLIC_API_URL=http://localhost:{ports.backend}",
                ],
            },
            "frontend": {
                "container_name": f"{worktree.compose_project}-frontend",
                "ports": [f"127.0.0.1:{ports.frontend}:4321"],
                "environment": [
                    f"PUBLIC_API_URL=http://localhost:{ports.backend}",
                ],
            },
            "worker": {
                "container_name": f"{worktree.compose_project}-worker",
                "volumes": [
                    "./backend:/app",
                    "./pipeline:/pipeline:ro",
                    f"{settings.shared_model_cache_volume}:/data/models/cache:ro",
                ],
            },
            "db": {
                "container_name": f"{worktree.compose_project}-db",
                "ports": [f"127.0.0.1:{ports.db}:5432"],
                "volumes": [f"{volumes.postgres}:/var/lib/postgresql/data"],
            },
            "redis": {
                "container_name": f"{worktree.compose_project}-redis",
                "ports": [f"127.0.0.1:{ports.redis}:6379"],
                "volumes": [f"{volumes.redis}:/data"],
            },
        },
        "volumes": {
            volumes.postgres: None,
            volumes.redis: None,
            volumes.uploads: None,
            settings.shared_model_cache_volume: {"external": True},
        },
    }

    # Write with comment header
    header = f"""# docker-compose.override.yml
# Auto-generated by worktree.py - DO NOT EDIT MANUALLY
# Worktree: {worktree.worktree_name}
# Branch: {worktree.branch}
# Generated: {datetime.now(timezone.utc).isoformat()}
#
# This file overrides docker-compose.yml with worktree-specific ports and volumes.
# The shared model cache volume ({settings.shared_model_cache_volume}) is mounted read-only.

"""
    yaml_content = yaml.dump(override, default_flow_style=False, sort_keys=False)
    output_path.write_text(header + yaml_content)


def check_ports_available(ports: PortConfig) -> dict[str, bool]:
    """Check if ports are available for binding.

    Args:
        ports: PortConfig to check

    Returns:
        Dict mapping port names to availability (True = available)
    """
    import socket

    results = {}

    for name, port in [
        ("frontend", ports.frontend),
        ("backend", ports.backend),
        ("db", ports.db),
        ("redis", ports.redis),
    ]:
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.bind(("127.0.0.1", port))
                results[name] = True
        except OSError:
            results[name] = False

    return results


def get_seed_sql() -> str | None:
    """Get contents of seed.sql if it exists.

    Returns:
        Seed SQL content or None if not found
    """
    seed_path = get_seed_path()
    if seed_path.exists():
        return seed_path.read_text()
    return None


def format_ports_display(ports: PortConfig) -> str:
    """Format ports for display.

    Args:
        ports: PortConfig to format

    Returns:
        Formatted string like "4321/8000/5432/6379"
    """
    return f"{ports.frontend}/{ports.backend}/{ports.db}/{ports.redis}"


def format_volumes_display(volumes: VolumeConfig) -> str:
    """Format volumes for display.

    Args:
        volumes: VolumeConfig to format

    Returns:
        Formatted string with volume names
    """
    return f"pg:{volumes.postgres}, redis:{volumes.redis}, uploads:{volumes.uploads}"
