"""Template management for configuration files.

Uses Jinja2 for template rendering with worktree-specific values.
"""

from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .config import settings
from .registry import Worktree


def get_template_env() -> Environment:
    """Get Jinja2 environment for templates.

    Returns:
        Configured Jinja2 Environment
    """
    template_dir = Path(__file__).parent / "templates"
    return Environment(
        loader=FileSystemLoader(template_dir),
        autoescape=select_autoescape(),
        trim_blocks=True,
        lstrip_blocks=True,
    )


def render_env_local(worktree: Worktree) -> str:
    """Render .env.local template for a worktree.

    Args:
        worktree: Worktree configuration

    Returns:
        Rendered .env.local content
    """
    env = get_template_env()

    try:
        template = env.get_template("env.local.j2")
    except Exception:
        # Fallback to inline template if file not found
        return _render_env_local_inline(worktree)

    return template.render(
        worktree=worktree,
        settings=settings,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )


def render_compose_override(worktree: Worktree) -> str:
    """Render docker-compose.override.yml template for a worktree.

    Args:
        worktree: Worktree configuration

    Returns:
        Rendered docker-compose.override.yml content
    """
    env = get_template_env()

    try:
        template = env.get_template("docker-compose.override.yml.j2")
    except Exception:
        # Fallback to inline template if file not found
        return _render_compose_override_inline(worktree)

    return template.render(
        worktree=worktree,
        settings=settings,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )


def _render_env_local_inline(worktree: Worktree) -> str:
    """Inline fallback for .env.local rendering."""
    return f"""# .env.local - Worktree-specific environment
# Auto-generated by worktree.py - DO NOT EDIT MANUALLY
# Worktree: {worktree.worktree_name}
# Branch: {worktree.branch}
# Generated: {datetime.now(timezone.utc).isoformat()}

# Docker Compose project name (isolates containers/networks)
COMPOSE_PROJECT_NAME={worktree.compose_project}

# Port overrides (external ports)
FRONTEND_PORT={worktree.ports.frontend}
BACKEND_PORT={worktree.ports.backend}
DB_PORT={worktree.ports.db}
REDIS_PORT={worktree.ports.redis}
CLOUDBEAVER_PORT={worktree.ports.cloudbeaver}

# API URL for frontend (must use external backend port)
PUBLIC_API_URL=http://localhost:{worktree.ports.backend}

# Volume names (isolated per worktree)
POSTGRES_VOLUME={worktree.volumes.postgres}
REDIS_VOLUME={worktree.volumes.redis}
UPLOADS_VOLUME={worktree.volumes.uploads}
CLOUDBEAVER_VOLUME={worktree.volumes.cloudbeaver}

# Model cache (shared, read-only in containers)
MODEL_CACHE_VOLUME={settings.shared_model_cache_volume}
"""


def _render_compose_override_inline(worktree: Worktree) -> str:
    """Inline fallback for docker-compose.override.yml rendering."""
    ports = worktree.ports
    volumes = worktree.volumes

    return f"""# docker-compose.override.yml
# Auto-generated by worktree.py - DO NOT EDIT MANUALLY
# Worktree: {worktree.worktree_name}
# Branch: {worktree.branch}
# Generated: {datetime.now(timezone.utc).isoformat()}
#
# This file provides worktree-specific port bindings and volume names.
# Ports are bound to 127.0.0.1 (localhost only) for security.
# The shared model cache volume ({settings.shared_model_cache_volume}) is mounted read-only.

services:
  backend:
    container_name: {worktree.compose_project}-backend
    ports:
      - "127.0.0.1:{ports.backend}:8000"
    volumes:
      - ./backend:/app
      - ./pipeline:/pipeline:ro
      - {settings.shared_model_cache_volume}:/data/models/cache:ro
      - {volumes.uploads}:/data/uploads
    environment:
      - PUBLIC_API_URL=http://localhost:{ports.backend}

  frontend:
    container_name: {worktree.compose_project}-frontend
    ports:
      - "127.0.0.1:{ports.frontend}:4321"
    environment:
      - PUBLIC_API_URL=http://localhost:{ports.backend}

  worker:
    container_name: {worktree.compose_project}-worker
    volumes:
      - ./backend:/app
      - ./pipeline:/pipeline:ro
      - {settings.shared_model_cache_volume}:/data/models/cache:ro

  db:
    container_name: {worktree.compose_project}-db
    ports:
      - "127.0.0.1:{ports.db}:5432"
    volumes:
      - {volumes.postgres}:/var/lib/postgresql/data

  redis:
    container_name: {worktree.compose_project}-redis
    ports:
      - "127.0.0.1:{ports.redis}:6379"
    volumes:
      - {volumes.redis}:/data

  cloudbeaver:
    container_name: {worktree.compose_project}-cloudbeaver
    ports:
      - "127.0.0.1:{ports.cloudbeaver}:8978"
    volumes:
      - {volumes.cloudbeaver}:/opt/cloudbeaver/workspace
    environment:
      CB_SERVER_NAME: "GTS {worktree.worktree_name}"

volumes:
  {volumes.postgres}:
  {volumes.redis}:
  {volumes.uploads}:
  {volumes.cloudbeaver}:
  {settings.shared_model_cache_volume}:
    external: true
"""


def write_worktree_configs(worktree: Worktree, worktree_path: Path) -> None:
    """Write all configuration files for a worktree.

    Args:
        worktree: Worktree configuration
        worktree_path: Path to the worktree
    """
    # Write .env.local (worktree-specific, loaded via env_file in docker-compose.yml)
    env_local_path = worktree_path / ".env.local"
    env_local_content = render_env_local(worktree)
    env_local_path.write_text(env_local_content)

    # Create .env from example if it doesn't exist
    env_path = worktree_path / ".env"
    env_example = worktree_path / ".env.example"
    if not env_path.exists() and env_example.exists():
        import shutil
        shutil.copy(env_example, env_path)

    # Write docker-compose.override.yml
    compose_override_path = worktree_path / "docker-compose.override.yml"
    compose_override_content = render_compose_override(worktree)
    compose_override_path.write_text(compose_override_content)
