"""Template management for worktree configuration files.

Generates per-worktree env files in the consolidated env model:

    compose.env           - committed static defaults (not managed here)
    .env.worktree         - gitignored, auto-generated by this module
    env.local.sh          - gitignored, seeded here on first setup (secrets)
    env.local.sh.example  - committed template (not managed here)

Legacy files (`.env`, `.env.local`, `.env.secrets`) are migrated into the new
layout on setup and then removed.
"""

from __future__ import annotations

import base64
import secrets
from datetime import UTC, datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .docker import is_traefik_running
from .registry import Worktree

LEGACY_ENV_FILES = (".env", ".env.local", ".env.secrets")

# Shell-exported secrets managed by env.local.sh. Order is preserved when
# rewriting the file.
SECRET_KEYS: tuple[str, ...] = (
    "DB_PASSWORD",
    "OAUTH_ENCRYPTION_KEY",
    "SECRET_KEY",
    "GTS_ADMIN_PASSWORD",
    "T3K_API_KEY",
)


def _generate_db_password() -> str:
    """Generate a secure random database password."""
    return secrets.token_urlsafe(24)


def _generate_fernet_key() -> str:
    """Generate a URL-safe base64-encoded 32-byte Fernet key."""
    return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode()


def _generate_hex_key(nbytes: int = 32) -> str:
    """Generate a hex-encoded random key."""
    return secrets.token_hex(nbytes)


def _get_public_url(worktree: Worktree) -> str:
    """Public URL for the worktree (Traefik HTTPS when running, else localhost)."""
    if is_traefik_running():
        subdomain = _get_traefik_subdomain(worktree)
        return f"https://{subdomain}.tone-shootout.com"
    return f"http://localhost:{worktree.ports.nginx}"


def _get_traefik_subdomain(worktree: Worktree) -> str:
    """Derive Traefik subdomain from the worktree branch."""
    branch = worktree.branch
    if branch == "main":
        return "main"
    if "/" in branch:
        prefix = branch.split("/")[0]
        if prefix.isdigit():
            return prefix
    if "-" in branch:
        prefix = branch.split("-")[0]
        if prefix.isdigit():
            return prefix
    sanitized = "".join(c if c.isalnum() or c == "-" else "-" for c in branch.lower())
    sanitized = sanitized.strip("-")[:20].rstrip("-")
    return sanitized or "main"


def _get_traefik_router_name(worktree: Worktree) -> str:
    return f"gts-{_get_traefik_subdomain(worktree)}"


def _get_compose_file() -> str:
    """Resolve COMPOSE_FILE for the current environment.

    Includes the traefik overlay when Traefik is currently running — matches
    the prior behaviour of `_ensure_compose_file_includes_traefik`.
    """
    parts = ["docker-compose.yml", "docker-compose.override.yml"]
    if is_traefik_running():
        parts.append("docker-compose.traefik.yml")
    return ":".join(parts)


def get_template_env() -> Environment:
    template_dir = Path(__file__).parent / "templates"
    return Environment(
        loader=FileSystemLoader(template_dir),
        autoescape=select_autoescape(),
        trim_blocks=True,
        lstrip_blocks=True,
    )


# ---------------------------------------------------------------------------
# .env.worktree
# ---------------------------------------------------------------------------


def render_env_worktree(worktree: Worktree) -> str:
    """Render .env.worktree content for a worktree."""
    env = get_template_env()
    ctx = {
        "worktree": worktree,
        "generated_at": datetime.now(UTC).isoformat(),
        "public_url": _get_public_url(worktree),
        "subdomain": _get_traefik_subdomain(worktree),
        "router_name": _get_traefik_router_name(worktree),
        "compose_file": _get_compose_file(),
    }
    try:
        template = env.get_template("env.worktree.j2")
    except Exception:
        return _render_env_worktree_inline(**ctx)
    return template.render(**ctx)


def _render_env_worktree_inline(
    *,
    worktree: Worktree,
    generated_at: str,
    public_url: str,
    subdomain: str,
    router_name: str,
    compose_file: str,
) -> str:
    return f"""# .env.worktree - Worktree-specific non-secret environment
# Auto-generated by worktree.py - DO NOT EDIT MANUALLY
# Worktree: {worktree.worktree_name}
# Branch: {worktree.branch}
# Generated: {generated_at}
#
# Secrets live in env.local.sh. Static defaults live in compose.env.

GTS_WORKTREE={worktree.worktree_name}
COMPOSE_PROJECT_NAME={worktree.compose_project}
COMPOSE_FILE={compose_file}

# Port overrides (external ports)
NGINX_PORT={worktree.ports.nginx}
ASTRO_PORT={worktree.ports.astro}
WEBAPP_PORT={worktree.ports.webapp}
DB_PORT={worktree.ports.db}
REDIS_PORT={worktree.ports.redis}
CLOUDBEAVER_PORT={worktree.ports.cloudbeaver}

# Public URL (Traefik HTTPS on server, localhost otherwise)
PUBLIC_URL={public_url}

# Traefik routing (for public internet deployment)
GTS_SUBDOMAIN={subdomain}
GTS_ROUTER_NAME={router_name}

# Volume names (isolated per worktree)
POSTGRES_VOLUME={worktree.volumes.postgres}
REDIS_VOLUME={worktree.volumes.redis}
CLOUDBEAVER_VOLUME={worktree.volumes.cloudbeaver}

# Observability (--profile observability)
GRAFANA_PORT={worktree.ports.grafana}
PROMETHEUS_PORT={worktree.ports.prometheus}
LOKI_PORT={worktree.ports.loki}
TEMPO_PORT={worktree.ports.tempo}
OTLP_GRPC_PORT={worktree.ports.otlp_grpc}
OTLP_HTTP_PORT={worktree.ports.otlp_http}
ALLOY_PORT={worktree.ports.alloy}

GRAFANA_VOLUME={worktree.volumes.grafana}
LOKI_VOLUME={worktree.volumes.loki}
TEMPO_VOLUME={worktree.volumes.tempo}
PROMETHEUS_VOLUME={worktree.volumes.prometheus}
"""


# ---------------------------------------------------------------------------
# docker-compose.override.yml
# ---------------------------------------------------------------------------


def render_compose_override(worktree: Worktree) -> str:
    env = get_template_env()
    ctx = {
        "worktree": worktree,
        "generated_at": datetime.now(UTC).isoformat(),
        "public_url": _get_public_url(worktree),
    }
    try:
        template = env.get_template("docker-compose.override.yml.j2")
    except Exception:
        return _render_compose_override_inline(**ctx)
    return template.render(**ctx)


def _render_compose_override_inline(
    *,
    worktree: Worktree,
    generated_at: str,
    public_url: str,
) -> str:
    ports = worktree.ports
    volumes = worktree.volumes
    return f"""# docker-compose.override.yml
# Auto-generated by worktree.py - DO NOT EDIT MANUALLY
# Worktree: {worktree.worktree_name}
# Branch: {worktree.branch}
# Generated: {generated_at}

services:
  nginx:
    container_name: {worktree.compose_project}-nginx
    ports:
      - "127.0.0.1:{ports.nginx}:80"

  webapp:
    container_name: {worktree.compose_project}-webapp
    ports:
      - "127.0.0.1:{ports.webapp}:8000"
    environment:
      - PUBLIC_URL={public_url}
      - CORS_ORIGINS={public_url}
      - GTS_AUTH_FILE=/worktrees/.gts-auth.json
      - GTS_STORAGE_ROOT=/app/storage
    volumes:
      - ../:/worktrees

  astro:
    container_name: {worktree.compose_project}-astro
    ports:
      - "127.0.0.1:{ports.astro}:4321"
    environment:
      - PUBLIC_URL={public_url}

  t3k-sync:
    container_name: {worktree.compose_project}-t3k-sync
    environment:
      - GTS_AUTH_FILE=/worktrees/.gts-auth.json
    volumes:
      - ../:/worktrees

  audio-worker:
    container_name: {worktree.compose_project}-audio-worker

  video-worker:
    container_name: {worktree.compose_project}-video-worker
    ports:
      - "127.0.0.1:{ports.video}:8002"

  db:
    container_name: {worktree.compose_project}-db
    ports:
      - "127.0.0.1:{ports.db}:5432"
    volumes:
      - {volumes.postgres}:/var/lib/postgresql

  cloudbeaver:
    container_name: {worktree.compose_project}-cloudbeaver
    ports:
      - "127.0.0.1:{ports.cloudbeaver}:8978"
    volumes:
      - {volumes.cloudbeaver}:/opt/cloudbeaver/workspace
    environment:
      CB_SERVER_NAME: "GTS {worktree.worktree_name}"

volumes:
  {volumes.postgres}:
  {volumes.cloudbeaver}:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.{worktree.offset}.0/24
"""


# ---------------------------------------------------------------------------
# env.local.sh (secrets, shell-sourced)
# ---------------------------------------------------------------------------


def _parse_shell_exports(path: Path) -> dict[str, str]:
    """Parse a shell file of `export KEY=value` lines into a dict."""
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :].strip()
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            values[key] = value
    return values


def _parse_dotenv(path: Path) -> dict[str, str]:
    """Parse a flat KEY=value dotenv file into a dict (no export prefix)."""
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :].strip()
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and value:
            values[key] = value
    return values


def _write_env_local_sh(path: Path, values: dict[str, str]) -> None:
    """Write env.local.sh with shell export lines in the canonical order."""
    lines = [
        "# env.local.sh - GTS project secrets (gitignored, human-managed)",
        "#",
        "# Sourced by .envrc (direnv) and scripts/dc before `docker compose` runs.",
        "# worktree.py seeds missing entries on first setup; it never overwrites",
        "# values you have edited.",
        "",
    ]
    for key in SECRET_KEYS:
        value = values.get(key, "")
        lines.append(f"export {key}={value}")
    # Preserve any unknown keys that were already present.
    extras = {k: v for k, v in values.items() if k not in SECRET_KEYS}
    if extras:
        lines.append("")
        lines.append("# Additional local values")
        for key, value in extras.items():
            lines.append(f"export {key}={value}")
    path.write_text("\n".join(lines) + "\n")


def _ensure_env_local_sh(worktree_path: Path) -> dict[str, str]:
    """Seed env.local.sh on first setup; preserve existing values thereafter.

    Returns the final set of secret values (used to prime POSTGRES on fresh
    databases via compose interpolation of `DB_PASSWORD`).
    """
    target = worktree_path / "env.local.sh"
    current = _parse_shell_exports(target)

    # Migrate from legacy dotenv files if env.local.sh is missing the value.
    legacy: dict[str, str] = {}
    for legacy_name in LEGACY_ENV_FILES:
        legacy.update(_parse_dotenv(worktree_path / legacy_name))

    def take(key: str) -> str:
        return current.get(key) or legacy.get(key) or ""

    values: dict[str, str] = {}
    values["DB_PASSWORD"] = take("DB_PASSWORD") or _generate_db_password()
    values["OAUTH_ENCRYPTION_KEY"] = (
        take("OAUTH_ENCRYPTION_KEY") or _generate_fernet_key()
    )
    values["SECRET_KEY"] = take("SECRET_KEY") or _generate_hex_key()
    values["GTS_ADMIN_PASSWORD"] = take("GTS_ADMIN_PASSWORD")
    values["T3K_API_KEY"] = take("T3K_API_KEY")

    # Carry forward any other keys the user already added to env.local.sh.
    for key, value in current.items():
        if key not in SECRET_KEYS:
            values[key] = value

    _write_env_local_sh(target, values)
    return values


# ---------------------------------------------------------------------------
# Public entry point: write all config files for a worktree
# ---------------------------------------------------------------------------


def write_worktree_configs(worktree: Worktree, worktree_path: Path) -> None:
    """Write .env.worktree, docker-compose.override.yml, seed env.local.sh.

    Idempotent — safe to call multiple times. Migrates legacy .env/.env.local/
    .env.secrets into env.local.sh + .env.worktree on first run, then removes
    the legacy files so only the new sources of truth remain.
    """
    _ensure_env_local_sh(worktree_path)

    env_worktree_path = worktree_path / ".env.worktree"
    env_worktree_path.write_text(render_env_worktree(worktree))

    compose_override_path = worktree_path / "docker-compose.override.yml"
    compose_override_path.write_text(render_compose_override(worktree))

    # Remove legacy dotenvs now that env.local.sh + .env.worktree own the data.
    for legacy_name in LEGACY_ENV_FILES:
        legacy_path = worktree_path / legacy_name
        if legacy_path.exists():
            legacy_path.unlink()
