"""Template management for configuration files.

Uses Jinja2 for template rendering with worktree-specific values.
"""

import os
import secrets
from datetime import UTC, datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .config import settings
from .docker import is_traefik_running
from .registry import Worktree


def generate_db_password() -> str:
    """Generate a secure random database password.

    Returns:
        A URL-safe random string suitable for database authentication.
    """
    return secrets.token_urlsafe(24)


def _get_public_url(worktree: Worktree) -> str:
    """Get the public URL for a worktree.

    Uses Traefik HTTPS URL if Traefik is running (server deployment),
    otherwise falls back to localhost with nginx port.

    Args:
        worktree: Worktree configuration

    Returns:
        Public URL (e.g., "https://main.tone-shootout.com" or "http://localhost:9000")
    """
    if is_traefik_running():
        subdomain = _get_traefik_subdomain(worktree)
        return f"https://{subdomain}.tone-shootout.com"
    return f"http://localhost:{worktree.ports.nginx}"


def get_template_env() -> Environment:
    """Get Jinja2 environment for templates.

    Returns:
        Configured Jinja2 Environment
    """
    template_dir = Path(__file__).parent / "templates"
    return Environment(
        loader=FileSystemLoader(template_dir),
        autoescape=select_autoescape(),
        trim_blocks=True,
        lstrip_blocks=True,
    )


def render_env_local(worktree: Worktree, db_password: str | None = None) -> str:
    """Render .env.local template for a worktree.

    Args:
        worktree: Worktree configuration
        db_password: Database password (auto-generated if not provided)

    Returns:
        Rendered .env.local content
    """
    env = get_template_env()

    # Generate password if not provided
    if db_password is None:
        db_password = generate_db_password()

    try:
        template = env.get_template("env.local.j2")
    except Exception:
        # Fallback to inline template if file not found
        return _render_env_local_inline(worktree, db_password)

    return template.render(
        worktree=worktree,
        settings=settings,
        db_password=db_password,
        generated_at=datetime.now(UTC).isoformat(),
        uid=os.getuid(),
        gid=os.getgid(),
        public_url=_get_public_url(worktree),
    )


def render_compose_override(worktree: Worktree) -> str:
    """Render docker-compose.override.yml template for a worktree.

    Args:
        worktree: Worktree configuration

    Returns:
        Rendered docker-compose.override.yml content
    """
    env = get_template_env()

    try:
        template = env.get_template("docker-compose.override.yml.j2")
    except Exception:
        # Fallback to inline template if file not found
        return _render_compose_override_inline(worktree)

    return template.render(
        worktree=worktree,
        settings=settings,
        generated_at=datetime.now(UTC).isoformat(),
        public_url=_get_public_url(worktree),
    )


def _get_traefik_subdomain(worktree: Worktree) -> str:
    """Derive Traefik subdomain from worktree info.

    Returns:
        Subdomain string (e.g., "main", "526", "feature-foo")
    """
    branch = worktree.branch

    # main branch gets "main" subdomain
    if branch == "main":
        return "main"

    # Issue branches (e.g., "526/epic-..." or "42-fix-bug") get issue number
    # Check for "N/..." pattern
    if "/" in branch:
        prefix = branch.split("/")[0]
        if prefix.isdigit():
            return prefix

    # Check for "N-..." pattern at start
    if "-" in branch:
        prefix = branch.split("-")[0]
        if prefix.isdigit():
            return prefix

    # Fallback: sanitize branch name for subdomain (max 20 chars, alphanumeric + hyphen)
    sanitized = "".join(c if c.isalnum() or c == "-" else "-" for c in branch.lower())
    sanitized = sanitized.strip("-")[:20].rstrip("-")
    return sanitized or "main"


def _get_traefik_router_name(worktree: Worktree) -> str:
    """Derive unique Traefik router name from worktree info.

    Returns:
        Router name (e.g., "gts-main", "gts-526")
    """
    subdomain = _get_traefik_subdomain(worktree)
    return f"gts-{subdomain}"


def _render_env_local_inline(worktree: Worktree, db_password: str) -> str:
    """Inline fallback for .env.local rendering."""
    # Note: db_password parameter kept for backwards compatibility but not used here
    # DB_PASSWORD and Traefik vars are written to .env instead (required for docker-compose interpolation)

    public_url = _get_public_url(worktree)

    return f"""# .env.local - Worktree-specific environment
# Auto-generated by worktree.py - DO NOT EDIT MANUALLY
# Worktree: {worktree.worktree_name}
# Branch: {worktree.branch}
# Generated: {datetime.now(UTC).isoformat()}

# NOTE: DB_PASSWORD and Traefik vars are in .env (required for docker-compose.yml variable interpolation)

# Host user (for containers that write to mounted volumes)
UID={os.getuid()}
GID={os.getgid()}

# Docker Compose project name (isolates containers/networks)
COMPOSE_PROJECT_NAME={worktree.compose_project}

# Port overrides (external ports)
# Note: Frontend port not exposed to host - access only through nginx
NGINX_PORT={worktree.ports.nginx}
WEBAPP_PORT={worktree.ports.webapp}
DB_PORT={worktree.ports.db}
REDIS_PORT={worktree.ports.redis}
CLOUDBEAVER_PORT={worktree.ports.cloudbeaver}

# Public URL (points to nginx entry point)
# Uses Traefik HTTPS URL on server, localhost for local development
PUBLIC_URL={public_url}

# Volume names (isolated per worktree)
POSTGRES_VOLUME={worktree.volumes.postgres}
REDIS_VOLUME={worktree.volumes.redis}
CLOUDBEAVER_VOLUME={worktree.volumes.cloudbeaver}

# =============================================================================
# Observability Stack (--profile observability)
# =============================================================================
# Start with: docker compose --profile observability up

# Observability ports (isolated per worktree)
GRAFANA_PORT={worktree.ports.grafana}
PROMETHEUS_PORT={worktree.ports.prometheus}
LOKI_PORT={worktree.ports.loki}
TEMPO_PORT={worktree.ports.tempo}
OTLP_GRPC_PORT={worktree.ports.otlp_grpc}
OTLP_HTTP_PORT={worktree.ports.otlp_http}
ALLOY_PORT={worktree.ports.alloy}

# Observability volumes (isolated per worktree)
GRAFANA_VOLUME={worktree.volumes.grafana}
LOKI_VOLUME={worktree.volumes.loki}
TEMPO_VOLUME={worktree.volumes.tempo}
PROMETHEUS_VOLUME={worktree.volumes.prometheus}
"""


def _render_compose_override_inline(worktree: Worktree) -> str:
    """Inline fallback for docker-compose.override.yml rendering."""
    ports = worktree.ports
    volumes = worktree.volumes
    public_url = _get_public_url(worktree)

    return f"""# docker-compose.override.yml
# Auto-generated by worktree.py - DO NOT EDIT MANUALLY
# Worktree: {worktree.worktree_name}
# Branch: {worktree.branch}
# Generated: {datetime.now(UTC).isoformat()}
#
# This file provides worktree-specific port bindings and volume names.
# Ports are bound to 127.0.0.1 (localhost only) for security.
#
# Entry point: http://localhost:{ports.nginx} (nginx serves static files + proxies to webapp)

services:
  nginx:
    container_name: {worktree.compose_project}-nginx
    ports:
      - "127.0.0.1:{ports.nginx}:80"

  webapp:
    container_name: {worktree.compose_project}-webapp
    ports:
      - "127.0.0.1:{ports.webapp}:8000"
    volumes:
      # App code (new uv workspace layout)
      - ./libs:/app/libs
      - ./apps/webapp:/app/apps/webapp
      - ./frontend/astro/dist:/app/static
      - ./src:/app/src
      - ./sources:/app/sources
      - ./tests:/app/tests
      - ./infrastructure/migrations:/app/infrastructure/migrations
      # Shared storage bind mount
      - ../gts-storage:/app/storage
      # Parent dir for shared auth file (.gts-auth.json)
      - ../:/worktrees
    environment:
      # All URLs point to nginx for consistent auth cookie handling
      # Uses Traefik HTTPS URL on server, localhost for local development
      - PUBLIC_URL={public_url}
      - CORS_ORIGINS={public_url}
      - GTS_AUTH_FILE=/worktrees/.gts-auth.json
      - GTS_STORAGE_ROOT=/app/storage

  # Astro is build-only (--profile build) - nginx serves pre-committed dist/ directly
  astro:
    container_name: {worktree.compose_project}-astro
    ports:
      - "127.0.0.1:{ports.astro}:4321"
    environment:
      - PUBLIC_URL={public_url}

  t3k-sync:
    container_name: {worktree.compose_project}-t3k-sync
    volumes:
      - ./libs:/app/libs
      - ./apps/t3k_sync:/app/apps/t3k_sync
      - ./apps/webapp:/app/apps/webapp
      - ./sources:/app/sources
      # Shared storage bind mount
      - ../gts-storage:/app/storage
      # Parent dir for shared auth file (.gts-auth.json)
      - ../:/worktrees
    environment:
      - GTS_AUTH_FILE=/worktrees/.gts-auth.json
      - GTS_STORAGE_ROOT=/app/storage

  audio-worker:
    container_name: {worktree.compose_project}-audio-worker
    volumes:
      - ./libs:/app/libs
      - ./apps/audio_worker:/app/apps/audio_worker
      # Shared storage bind mount
      - ../gts-storage:/app/storage
    environment:
      - GTS_STORAGE_ROOT=/app/storage

  video-worker:
    container_name: {worktree.compose_project}-video-worker
    ports:
      - "127.0.0.1:{ports.video}:8002"
    volumes:
      - ./libs/core:/app/libs/core
      - ./libs/video:/app/libs/video
      - ./apps/video_worker:/app/apps/video_worker
      - ./apps/webapp:/app/apps/webapp
      - ./sources:/app/sources
      # Shared storage bind mount
      - ../gts-storage:/app/storage
    environment:
      - GTS_STORAGE_ROOT=/app/storage

  db:
    container_name: {worktree.compose_project}-db
    ports:
      - "127.0.0.1:{ports.db}:5432"
    volumes:
      - {volumes.postgres}:/var/lib/postgresql/data

  cloudbeaver:
    container_name: {worktree.compose_project}-cloudbeaver
    ports:
      - "127.0.0.1:{ports.cloudbeaver}:8978"
    volumes:
      - {volumes.cloudbeaver}:/opt/cloudbeaver/workspace
    environment:
      CB_SERVER_NAME: "GTS {worktree.worktree_name}"

volumes:
  {volumes.postgres}:
  {volumes.cloudbeaver}:

# Override subnet to avoid conflicts between worktrees
# Each worktree gets a unique subnet based on its offset: 10.10.{{offset}}.0/24
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.{worktree.offset}.0/24
"""


def _get_existing_db_password(env_path: Path) -> str | None:
    """Extract existing DB_PASSWORD from .env file if present.

    Args:
        env_path: Path to .env file

    Returns:
        Existing password or None if not found
    """
    if not env_path.exists():
        return None

    for line in env_path.read_text().splitlines():
        line = line.strip()
        if line.startswith("DB_PASSWORD=") and not line.startswith("#"):
            password = line.split("=", 1)[1].strip()
            if password:
                return password
    return None


def write_worktree_configs(worktree: Worktree, worktree_path: Path) -> None:
    """Write all configuration files for a worktree.

    This function is idempotent:
    - Preserves existing DB_PASSWORD to avoid breaking running databases
    - Only generates new password on fresh setup
    - Safe to call multiple times

    Args:
        worktree: Worktree configuration
        worktree_path: Path to the worktree
    """
    env_path = worktree_path / ".env"
    env_example = worktree_path / ".env.example"

    # CRITICAL: Preserve existing password to avoid breaking running databases
    # Only generate a new password if one doesn't exist
    existing_password = _get_existing_db_password(env_path)
    db_password = existing_password or generate_db_password()

    # Write .env.local (worktree-specific, loaded via env_file in docker-compose.yml)
    env_local_path = worktree_path / ".env.local"
    env_local_content = render_env_local(worktree, db_password)
    env_local_path.write_text(env_local_content)

    # Create .env from example if it doesn't exist
    if not env_path.exists() and env_example.exists():
        import shutil

        shutil.copy(env_example, env_path)

    # Ensure DB_PASSWORD is in .env (only updates if missing or different)
    _update_env_password(env_path, db_password)

    # Ensure Traefik variables are in .env (for docker-compose.traefik.yml)
    _update_env_traefik(env_path, worktree)

    # Write docker-compose.override.yml
    compose_override_path = worktree_path / "docker-compose.override.yml"
    compose_override_content = render_compose_override(worktree)
    compose_override_path.write_text(compose_override_content)

    # Note: nginx.dev.conf is no longer generated - docker-compose.yml now mounts
    # nginx.conf.template directly and uses envsubst at container startup


def _update_env_password(env_path: Path, db_password: str) -> None:
    """Update or add DB_PASSWORD in .env file.

    Args:
        env_path: Path to .env file
        db_password: Generated password to set
    """
    if not env_path.exists():
        # Create minimal .env with just the password
        env_path.write_text(
            f"# Auto-generated database password (do not commit this file)\n"
            f"DB_PASSWORD={db_password}\n"
        )
        return

    # Read existing content
    content = env_path.read_text()
    lines = content.splitlines()

    # Find and update DB_PASSWORD line, or add it
    password_line = f"DB_PASSWORD={db_password}"
    found = False

    for i, line in enumerate(lines):
        # Skip comments and empty lines
        stripped = line.strip()
        if stripped.startswith("DB_PASSWORD="):
            lines[i] = password_line
            found = True
            break
        # Also handle commented out DB_PASSWORD
        if stripped.startswith("# DB_PASSWORD="):
            lines[i] = password_line
            found = True
            break

    if not found:
        # Add after the first comment block or at the top
        # Find first non-comment, non-empty line
        insert_pos = 0
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped and not stripped.startswith("#"):
                insert_pos = i
                break
            insert_pos = i + 1

        lines.insert(insert_pos, password_line)
        if insert_pos > 0 and lines[insert_pos - 1].strip():
            lines.insert(insert_pos, "")  # Add blank line before

    env_path.write_text("\n".join(lines) + "\n")


def _update_env_traefik(env_path: Path, worktree: Worktree) -> None:
    """Update or add Traefik variables in .env file.

    These are required for docker-compose.traefik.yml to work correctly.

    Args:
        env_path: Path to .env file
        worktree: Worktree configuration
    """
    if not env_path.exists():
        return  # Should not happen, _update_env_password creates it

    subdomain = _get_traefik_subdomain(worktree)
    router_name = _get_traefik_router_name(worktree)

    content = env_path.read_text()
    lines = content.splitlines()

    # Variables to update/add
    traefik_vars = {
        "GTS_SUBDOMAIN": subdomain,
        "GTS_ROUTER_NAME": router_name,
    }

    # Check which variables need to be added
    for var_name, var_value in traefik_vars.items():
        var_line = f"{var_name}={var_value}"
        found = False

        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith(f"{var_name}="):
                lines[i] = var_line
                found = True
                break

        if not found:
            # Add at end of file
            if lines and lines[-1].strip():
                lines.append("")  # Add blank line before if needed
            lines.append(var_line)

    env_path.write_text("\n".join(lines) + "\n")
