# Shared derivation for the GTS worktree-engine hooks.
# Sourced by provision.sh / gate.sh / teardown.sh. Derives the per-worktree
# compose contract from the resources the engine injects (WORKTREE_SLOT and the
# WORKTREE_PORT_* values), with no .env.worktree and no shared state file: every
# hook is self-contained and re-derives the same contract from the same inputs.
#
# The engine runs each hook with cwd = the feature worktree checkout and the
# WORKTREE_* handoff in the environment. Slots are integers in [1, 256); main
# (slot 0) is never provisioned by the engine.

# Run from the feature checkout regardless of how the hook was invoked.
WT_ROOT="${WORKTREE_PATH:-$(pwd)}"
cd "$WT_ROOT"

SLOT="${WORKTREE_SLOT:?WORKTREE_SLOT not injected by the engine}"
WEBAPP_PORT="${WORKTREE_PORT_WEBAPP:?WORKTREE_PORT_WEBAPP not injected}"
DB_PORT="${WORKTREE_PORT_DB:?WORKTREE_PORT_DB not injected}"

# Compose project -> container names (gts-<slot>-<service>, auto-derived) and
# GTS_WORKTREE -> the base compose's named volumes (gts-postgres-<slot>).
export COMPOSE_PROJECT_NAME="gts-${SLOT}"
export GTS_WORKTREE="${SLOT}"
export USER_UID="$(id -u)" USER_GID="$(id -g)"

# A fresh feature worktree has no gitignored env.local.sh (it is not committed).
# Source it when present; otherwise mint an ephemeral Fernet key so the gate's
# encryption round-trip tests pass, and leave DB_PASSWORD to the compose default
# (consistent across db and webapp: ${DB_PASSWORD:-gts_dev_password}).
if [ -f env.local.sh ]; then
    # shellcheck disable=SC1091
    source env.local.sh
fi
: "${OAUTH_ENCRYPTION_KEY:=$(python3 -c 'import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())')}"
export OAUTH_ENCRYPTION_KEY

# Provision's generated per-worktree artefacts (gitignored). The override is the
# only compose layer beyond the base; .env.worktree is gone.
RUN_DIR=".worktree-run"
OVERRIDE="$RUN_DIR/docker-compose.override.yml"
PER_STORAGE="$RUN_DIR/storage"

# Compose invocation shared by every hook: base + the per-worktree override, with
# committed static defaults from compose.env. Secrets reach interpolation through
# the sourced shell environment (env.local.sh or the ephemeral Fernet above).
wt_dc() { docker compose -f docker-compose.yml -f "$OVERRIDE" --env-file compose.env "$@"; }

# Generate the per-worktree override. Publishes only the two declared host ports
# (nginx/astro carry no host port, so they never collide with main's 9000/4321).
# Storage: the base whole-mounts ../gts-storage:/app/storage (shared RW); these
# subpath binds shadow the write trees with empty per-worktree dirs and graft the
# large data read-only, so a feature stack never writes main's storage and never
# copies models/audio. Per-project default networks isolate worktrees from each
# other without a custom subnet.
wt_generate_override() {
    mkdir -p "$RUN_DIR" \
        "$PER_STORAGE/uploads" "$PER_STORAGE/videos" \
        "$PER_STORAGE/logs" "$PER_STORAGE/source_downloads"
    cat > "$OVERRIDE" <<EOF
# Auto-generated by scripts/worktree/_derive.sh - per-worktree compose contract.
# Project: $COMPOSE_PROJECT_NAME (slot $SLOT). Driven by WORKTREE_SLOT + WORKTREE_PORT_*.
# Regenerated idempotently by every hook; do not edit.
services:
  webapp:
    ports:
      - "127.0.0.1:$WEBAPP_PORT:8000"
    volumes:
      - $PER_STORAGE/uploads:/app/storage/uploads
      - $PER_STORAGE/videos:/app/storage/videos
      - $PER_STORAGE/logs:/app/storage/logs
      - $PER_STORAGE/source_downloads:/app/storage/source_downloads
      - ../gts-storage/models:/app/storage/models:ro
      - ../gts-storage/audio:/app/storage/audio:ro
    environment:
      - PUBLIC_URL=http://localhost:$WEBAPP_PORT
      - CORS_ORIGINS=http://localhost:$WEBAPP_PORT
      - GTS_STORAGE_ROOT=/app/storage
  db:
    ports:
      - "127.0.0.1:$DB_PORT:5432"
EOF
}

wt_generate_override
